### ISSUE TITLE
Embed Environment Variables into the build

### ISSUE THREAD

**Issue by alexandredev3** [egoist/tsup#1030]
Currently, the only way to tsup statically embed environment variables into the build is by adding them in the config file or using the `--env` cli flag:

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  env: {
    SUPABASE_PUBLIC_KEY: "blahblah"
  }
})
```
```bash
$ tsup src/index.ts --env.SUPABASE_PUBLIC_KEY blahblah
```
However, this process can become cumbersome, especially when dealing with multiple environment variables. What if we could simplify it by adding support for `.env` files similar to [vitejs](https://vitejs.dev/guide/env-and-mode.html#production-replacement)? This would allow users to simply pass the path of their `.env` file:
```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  env: ".env" // .env.local, .env.development, .env.production ...
})
```
or
```bash
$ tsup src/index.ts --env .env
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1030">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1030/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1030/pledge.svg">
</picture>
</a>

**Comment by branchard** [comment]
You can just do it by hand:
```typescript
import {defineConfig} from 'tsup';
import dotenv from 'dotenv';

export default defineConfig({
    entry: ['src/index.ts'],
    env: dotenv.config().parsed,
});
```

**Comment by alexandredev3** [comment]
> You can just do it by hand:
> 
> ```ts
> import {defineConfig} from 'tsup';
> import dotenv from 'dotenv';
> 
> export default defineConfig({
>     entry: ['src/index.ts'],
>     env: dotenv.config().parsed,
> });
> ```

Yep, I ended up doing it that way

```ts
  import { defineConfig } from 'tsup';
  import "@dotenvx/dotenvx";
  
  export default defineConfig({
    clean: true,
    target: 'es2020',
    dts: true,
    env: {
      SUPABASE_CLIENT_URL: process.env.SUPABASE_CLIENT_URL!,
      SUPABASE_CLIENT_PUBLIC_KEY: process.env.SUPABASE_CLIENT_PUBLIC_KEY!,
    },
    format: [
      'cjs',
      'esm'
    ]
  });
```

```bash
$ npm run dotenvx run --env-file=.env.local -- tsup ./**/*.ts --watch
```

Thank you though! 🚀
