### ISSUE TITLE
[bug] Tsup removes JSDOC

### ISSUE THREAD

**Issue by vitalics** [egoist/tsup#1059]
TSUP automatically removes JSDOC comments. In my project it's essential

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1059">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1059/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1059/pledge.svg">
</picture>
</a>

**Comment by ocavue** [comment]
This is a limitation from the upstream ESBuild ([issue link](https://github.com/evanw/esbuild/issues/1439)).
