### ISSUE TITLE
Is it possible to build a react component with css.module ?

### ISSUE THREAD

**Issue by h2ck4u** [egoist/tsup#1101]
hello. I'm creating a react library using tsup in a turborepo environment.

I checked that the bundle result contains the classname of the cssModule as an object.

```tsx
// src/atom/input/input.module.css
var input_default = {
  warn: "input_warn",
  invalid: "input_invalid",
  disabled: "input_disabled",
  md: "input_md",
  sm: "input_sm",
  lg: "input_lg",
};
```

I deployed the bundled library as an npm package and imported it in MyApp to use it.

```tsx
import MyInput from '@myreact-lib/input''

const com = () => {
  return <MyInput size="lg"/>
}

//render result
<input className="input_lg"> </input>
```

When I checked the rendered component, the style was not applied.

This is because the stylesheet included in input.module.css was not included in the bundle.

Is there a way to include styles when deploying a React component library using TSUP?
Please help me.

```tsx
// this is my tsup.config.js
export default defineConfig({
  dts: true,
  sourcemap: false,
  clean: true,
  treeshake: true,
  skipNodeModulesBundle: false,
  format: ['esm', 'cjs'],
  external: ['react', 'react-dom'],
  loader: {
    '.css': 'default'
  },
  tsconfig: './tsconfig.json',
});

```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1101">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1101/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1101/pledge.svg">
</picture>
</a>

**Comment by h2ck4u** [comment]
i solved with tsup.config.js

i change loader 'css': 'default' > 'css: 'copy',
```
  loader: {
    '.css': 'default'
  },
```

**Comment by mayank1513** [comment]
You can also check out this repo - https://github.com/react18-tools/turborepo-template/

**Comment by gopal-virtual** [comment]
while @h2ck4u's solution works, but it doesn't 
* minify the css
* puts the css inside a subfolder if needed.

on the other hand `local-css` option does solve the above two problem, but not automatically imported inside the js file, so I've to manually import it in consumer app.

**Comment by mayank1513** [comment]
I have built a plugin for this - https://github.com/react18-tools/esbuild-plugin-react18-css/

Example - https://github.com/react18-tools/turborepo-template/

**Comment by gopal-virtual** [comment]
@mayank1513, appreciate your effort. But your library still has the last problem I mentioned (i.e. manual import for css is needed). I am looking for css injection in JS.

**Comment by mayank1513** [comment]
> @mayank1513, appreciate your effort. But your library still has the last problem I mentioned (i.e. manual import for css is needed). I am looking for css injection in JS.

Noted! Please create a feature request. I think this is very much doable and in the next version we could try to have this feature as well.

**Comment by anoop0567** [comment]
@gopal-virtual @mayank1513 any update on this or any workaround to full fill the requirement of injecting module css
