### ISSUE TITLE
Type Doc is 404

### ISSUE THREAD

**Issue by tomgao365** [egoist/tsup#1145]
[Type Doc](https://paka.dev/npm/tsup) is 404.
It needs a replacement.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1145">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1145/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1145/pledge.svg">
</picture>
</a>

**Comment by bburns** [comment]
This works - https://www.jsdocs.io/package/tsup

---

What is paka.dev anyway? The site just says 

> 404: NOT_FOUND
> Code: DEPLOYMENT_NOT_FOUND

https://x.com/pakadocs

Paka (@pakadocs) / X
X · pakadocs
50+ followers
Paka. @pakadocs. Bringing better docs to the JavaScript & TypeScript ecosystem. paka.dev Joined May 2021. 0 Following · 51 Followers · Posts · Replies.

But no posts?

**Comment by Seroxdesign** [comment]
Same issue can't find ```import build from tsup``` docs, it's a 404

https://www.paka.dev/

**Comment by sxzz** [comment]
Besides jsdocs.io, are there other types of documentation for JS libraries? I'm considering switching to another one.
