### ISSUE TITLE
Got `Cannot find module '@swc/core'` error with v8.1.1

### ISSUE THREAD

**Issue by ntnyq** [egoist/tsup#1157]
[Reproduction](https://github.com/ntnyq-dev/repro-tsup-swc-peer-dep-issue)

**Workaround**:

1. Add @swc/core as a dev dependencies mannually.
2. Keep still in version <=8.1.0 for now.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1157">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1157/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1157/pledge.svg">
</picture>
</a>

**Comment by ntnyq** [comment]
There has already had a PR https://github.com/egoist/tsup/pull/1156 about it.

This issue will close until it's addressed.

**Comment by ArcherGu** [comment]
same error, I have to add `@swc/core` to my devDependencies

**Comment by schtauffen** [comment]
I downgraded to 8.1.0 for now

**Comment by hugocxl** [comment]
A hotfix should be deployed as possible as it breaks most existing build processes using `tsup`

**Comment by sxzz** [comment]
Try `tsup@8.1.2` & should be fixed.
