### ISSUE TITLE
Critical bug in version v8.2.1

### ISSUE THREAD

**Issue by devcaeg** [egoist/tsup#1165]
I have the following configuration to create the `build` of my application, until version `v8.2.0` everything worked correctly, but since version `v8.2.1` I can't generate the `build` because the console is filled with messages like the following:

```ts
import { build } from 'tsup';

await build({
  bundle: true,
  clean: true,
  dts: false,
  entry: ['src/**/*.ts', '!src/**/*.d.ts', '!src/types/**/*.ts', '!src/index.ts'],
  external: ['bun'],
  format: 'esm',
  minify: true,
  outDir: 'dist',
  sourcemap: false,
  target: 'esnext',
  treeshake: true,
});
```

```console
✘ [ERROR] No loader is configured for ".map" files: node_modules/@typescript-eslint/eslint-plugin/dist/rules/prefer-includes.js.map

✘ [ERROR] No loader is configured for ".map" files: node_modules/openai/resources/audio/translations.d.ts.map

✘ [ERROR] No loader is configured for ".map" files: node_modules/@typescript-eslint/eslint-plugin/dist/rules/ban-ts-comment.js.map

✘ [ERROR] No loader is configured for ".map" files: node_modules/@typescript-eslint/scope-manager/dist/definition/index.js.map

✘ [ERROR] No loader is configured for ".map" files: node_modules/@typescript-eslint/scope-manager/dist/scope/index.js.map

✘ [ERROR] No loader is configured for ".map" files: node_modules/tsc-alias/dist/utils/import-path-resolver.js.map

✘ [ERROR] No loader is configured for ".map" files: node_modules/@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables.js.map
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1165">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1165/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1165/pledge.svg">
</picture>
</a>

**Comment by fahmij8** [comment]
Yes, I'm having the same exact problem 
probably need to rollback @egoist?

**Comment by egoist** [comment]
Fixed in https://github.com/egoist/tsup/releases/tag/v8.2.2
