### ISSUE TITLE
Cannot start service: Host version "0.17.19" does not match binary version "0.18.20"

### ISSUE THREAD

**Issue by Simon-He95** [egoist/tsup#1175]
<img width="999" alt="image" src="https://github.com/user-attachments/assets/2388923b-2b96-4e10-83d6-b5cb3b6637be">

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1175">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1175/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1175/pledge.svg">
</picture>
</a>

**Comment by iki** [comment]
Remove `node_modules/esbuild` and reinstall:

```sh
[ -d node_modules/esbuild ] && rm -rf node_modules/esbuild; pnpm install
```
