### ISSUE TITLE
upgrade chokidar to v4

### ISSUE THREAD

**Issue by SuperchupuDev** [egoist/tsup#1200]
uses only one subdependency compared to 13, v4 dropped support for glob patterns but that behavior can still be replicated with no extra deps since tsup already uses a globbing library

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/1200">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/1200/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/1200/pledge.svg">
</picture>
</a>

**Comment by sxzz** [comment]
I'd like to accept a PR
