### ISSUE TITLE
No support for spread operator

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#15]
```ts
// LN 26
const { $extend, ...grants } = grant;
```

```bash
[esbuild] (app/modules/get-permissions.ts:26:19) This syntax is from ES2018 and is not available in ES2017
```

**Comment by OmgImAlexis** [comment]
This is odd since I'm using the latest version of tsup which has `ES2018` set in the tsconfig. Is there maybe another place that needs to be set too?

https://github.com/evanw/esbuild#syntax-support

**Comment by egoist** [comment]
That tsconfig is only used to compile tsup itself.

Try `tsup --target es2018`

**Comment by OmgImAlexis** [comment]
Oh duh. It's been a long day.

That worked perfectly.
