### ISSUE TITLE
Support for star export

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#17]
Ref: https://github.com/Swatinem/rollup-plugin-dts/issues/94

**Comment by OmgImAlexis** [comment]
@egoist can we get `node-resolve` added in here as per https://github.com/Swatinem/rollup-plugin-dts/issues/94#issuecomment-636441183?

I noticed the bundle can handle `import x from './x-dir';` where `x-dir` is a directory with a `index.ts` in it but the `dts` stuff can't so maybe it needs access to the plugin for correct resolution?

**Comment by egoist** [comment]
use `--dts-bundle` flag

**Comment by egoist** [comment]
Should work now with `--dts-resolve`.
