### ISSUE TITLE
export issues with cjs

### ISSUE THREAD

**Issue by tbnritzdoge** [egoist/tsup#255]
When I bundle
```ts
import { CentraRequest, HTTPMethod } from './lib/CentraRequest';
import { URL } from 'url';
/**
 *
 *
 * @param {(URL | string)} url
 * @param {HTTPMethod} [method='GET']
 */
export = (url: URL | string, method: HTTPMethod = 'GET') => new CentraRequest(url, method);;
``` 

I get module.exports.default = the function rather than module.exports = function which is the intended behavior.

Are there any solutions or workarounds to this?

**Comment by egoist** [comment]
The workaround is using `export default`:

```ts
const lib = () => {}
export default lib

if (typeof module !== 'undefined') {
  module.exports = lib
  module.exports.default = lib
}
```

**Comment by egoist** [comment]
here's why it's transpiled to `module.exports.default`:

to use the [code splitting feature in esbuild](https://esbuild.github.io/api/#splitting) we have to transpile the ts code to esm (esbuild's code splitting is only supported by esm format), so `export =` gets transpiled to `export default`, then we transpile the esm code to cjs code, which results in `module.exports.default`.

**Comment by egoist** [comment]
I guess I can add a cli flag to disable code splitting (since you might not need it) and let esbuild directly transpile the ts code to cjs format, which will gives you proper `module.exports = ` statement.

**Comment by egoist** [comment]
Try the `--no-splitting` flag.
