### ISSUE TITLE
Transpiled to `exports.default` instead of `module.exports.default`

### ISSUE THREAD

**Issue by yaquawa** [egoist/tsup#283]
I've read https://tsup.egoist.sh/#faq , but it seems like the default behavior is outputting `exports.default` but not `module.exports.default` ?

**Comment by ElMassimo** [comment]
Related: [cjs/esm interoperability patch](https://github.com/antfu/unplugin-icons/blob/main/scripts/postbuild.ts#L17-L18).

It would be really cool if `tsup` supported this behavior out of the box, perhaps behind a flag.

**Comment by egoist** [comment]
> I've read tsup.egoist.sh/#faq , but it seems like the default behavior is outputting exports.default but not module.exports.default ?

Yeah.

> Related: cjs/esm interoperability patch.

> It would be really cool if tsup supported this behavior out of the box, perhaps behind a flag.

not sure about that, it's already trivial if you somehow want this:

```js
const mod = require('./dist/index')
module.exports = mod
Object.assign(module.exports, mod)
```
