### ISSUE TITLE
Mark all node_modules as external

### ISSUE THREAD

**Issue by PabloSzx** [egoist/tsup#289]
`tsup` right now has an issue with node modules with files inside the module that are not the main file (for example, `import { foo } from "bar/baz"`), and it always tries to bundle them, which pretty much always is a non-desired behavior. And even breaks when outputting to esm, since it tries to bundle commonjs inside the esm modules

`evanw` gave a solution as a plugin mentioned here: https://github.com/evanw/esbuild/issues/619#issuecomment-751995294

I tested it locally and it works fine, but I would need some feedback in how to enable this behaviour, the cleanest one I could thought off is reading the `moduleResolution: "node"` in the `tsconfig`, since having that it should assume you are dealing with outputting for Node.js, but maybe a very small flag in the CLI would be a good solution too, like "tsup src/index.ts --node"

**Comment by egoist** [comment]
Just added a simple fix to exclude files inside dependencies too: https://github.com/egoist/tsup/releases/tag/v4.9.2

**Comment by PabloSzx** [comment]
Thank you @egoist, I just tested it in a couple places and it works as expected 👍

**Comment by PabloSzx** [comment]
I realized that this fix is not 100% reliable, in Windows it worked, but in macOS it failed for some reason, and tried to bundle monorepo projects

**Comment by PabloSzx** [comment]
to give some context, I am using tsup in projects to use ESM is Node.js, with great DX for development and production

**Comment by egoist** [comment]
do you have a demo I can test? anyway a flag for that is indeed desired for some use cases, but I think --no-node-resolve would be a more appropriate name, kinda like the opposite of rollup-plugin-node-resolve. `moduleResolution: 'node'` kinda gives the feeling that node modules should be resolved, hence bundled.

**Comment by egoist** [comment]
btw that's not the default behavior because it's useful to bundle some dependencies to have a smaller package size.

**Comment by PabloSzx** [comment]
> btw that's not the default behavior because it's useful to bundle some dependencies to have a smaller package size.

for libraries yes, but for Node.js applications / apis that's not the case, and it breaks esm support as I mentioned



> do you have a demo I can test? anyway a flag for that is indeed desired for some use cases, but I think --no-node-resolve would be a more appropriate name, kinda like the opposite of rollup-plugin-node-resolve. `moduleResolution: 'node'` kinda gives the feeling that node modules should be resolved, hence bundled.

The flag needs to be shorter, or at least the cli offer a shortcut, my intention is to"advertise"/recommend tsup in an upcoming projects related to the development of GraphQL APIs, and simple examples having very long CLI scripts is a no-no.

Another solution I can think off is to offer an alternative cli bin, "tsup-node" that includes this behavior

**Comment by PabloSzx** [comment]
> do you have a demo I can test?.

It's not as straight forward as I'd like, and as I mentioned it's inconsistent, and the end-goal of this is using tsup as a Node.js applications development tool, where bundling packages is not relevant and undesired

**Comment by mindplay-dk** [comment]
> `tsup` right now has an issue with node modules with files inside the module that are not the main file (for example, `import { foo } from "bar/baz"`), and it always tries to bundle them, which pretty much always is a non-desired behavior.

Why? I thought bundling dependencies was the point of using a bundler?

I found this in the README as well:

> By default `tsup` bundles all `import`-ed modules but `dependencies` in your `packages.json` are always excluded

This also doesn't explain why? (It probably should?)

My simple use-case is a library that internally uses `fast-deep-equal` - I consider that an implementation detail, not something someone should need to install; I want to ship a single `.js` file with no dependencies, with the expected version of this library built-in, and so on.

Is this unusual? It seems to be default behavior of other bundlers, e.g. webpack, rollup - and for that matter esbuild, which it sounds like you needed a plugin or workaround to suppress that?

In my experience, `dependencies` are usually bundled by default, unless listed as `externals` somehow - whereas `peerDependencies` are not?

I found this very confusing - and the manual doesn't seem to mention any opt-out?

If you're not going to follow the typical pattern of bundlers bundling by default, with `externals` as an opt-out, perhaps you might consider an `internals` switch to reverse this behavior for libraries where you do want to bundle something?

**Comment by mindplay-dk** [comment]
For the recording, moving this dependency to `devDependencies` fixed it - and it's probably the right solution, since this is not a dependency in the npm sense, but only a build-time dependency.

Putting it there feels a bit odd, as it's not the advice you're normally given - but it also kind of makes sense, given that it won't be an install-time dependency.

If that's the correct approach, this should probably be mentioned in documentation? It probably won't be obvious to most users, given that this is not how most bundlers behave by default?

**Comment by kklas** [comment]
@mindplay-dk I have a similar use-case where I want everything to be bundled to a single file (deploying a worker to cloudflare) and I got to a very elegant solution which is to just use esbuild directly `esbuild src/main.ts --bundle --minify --platform=node --target=node17 --outfile=dist/main.js`
