### ISSUE TITLE
Using esbuild plugin to support `emitDecoratorMetadata`

### ISSUE THREAD

**Issue by kfirba** [egoist/tsup#298]
Hey,

How can I register esbuild native plugins to add support for `emitDecoratorMetadata`?
There is a package that solves this: [@anatine/esbuild-decorators](https://github.com/anatine/esbuildnx/tree/main/packages/esbuild-decorators)

Thanks!

**Comment by kfirba** [comment]
@egoist This plugin just runs a regex across all files. It's relatively fast :)

**Comment by egoist** [comment]
ah i see, tsc is just an option https://github.com/anatine/esbuildnx/blob/c265a84a9ebb4d190a955fa0ed3b383c022f7d9c/packages/esbuild-decorators/src/lib/esbuild-decorators.ts#L59

**Comment by egoist** [comment]
so you can use `tsup.config.js` to add esbuild plugins, tho this is not yet documented and might change in the future:

```js
module.exports = {
  esbuildPlugins: [/* your plugins */]
}
```

**Comment by egoist** [comment]
if the esbuild-decorators is proven to be stable, I will consider adding it to this library directly.

**Comment by kfirba** [comment]
@egoist What do you mean by "proven to be stable"?
I've used it in any project that depends on decorators. NestJS depends on decorators and every esbuild implementation of building NestJS app uses `esbuild-decorators`. Are you looking for something else?

**Comment by kfirba** [comment]
@egoist I see. I haven't used this feature outside TypeORM/NestJS. However, they both use decorators quite extensively. Let me know if you want to know anything about it!

**Comment by twocucao** [comment]
When you want to use emitDecoratorMetadata, and use some packages like `reflect-metadata` `typegraphql`

You need to config like this

```
// tsconfig.json
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
  }
}

```


```
// tsup.config.js

import type { Options } from "tsup";
import { esbuildDecorators } from "@anatine/esbuild-decorators";
export const tsup: Options = {
  splitting: true,
  sourcemap: true,
  clean: true,
  esbuildPlugins: [
    esbuildDecorators(),
  ],
  entryPoints: ["src/index.ts"],
};

```

**Comment by egoist** [comment]
Just checked it again, seesm it IS using the typescript compiler: https://github.com/anatine/esbuildnx/blob/f734cff19d9dd93e94441a01aaafac639e668459/packages/esbuild-decorators/src/lib/esbuild-decorators.ts#L77

**Comment by egoist** [comment]
Now we're using SWC to emit decorator metadata in v5.10.0, make sure you have `@swc/core` installed in your project.

**Comment by Lioness100** [comment]
Is there any reason you didn't use the regex? It seems like kinda a waste to me to use swc for my whole project when I only use decorators in a few files.
