### ISSUE TITLE
[Question] Support config file like tsup.config.js

### ISSUE THREAD

**Issue by harrytran998** [egoist/tsup#300]
Hi Egoist, thank you for the great lib! But I wonder how about this?
`tsup.config.js`
```js
module.export = {
 target: 'es2021',
 sourcemap: true,
 format: ['esm','cjs']
 ....
}
```

**Comment by PabloSzx** [comment]
if @egoist agrees with this feature I can work on implementing it 👍

**Comment by egoist** [comment]
you can already use `tsup.config.js`, it's just not documented.

**Comment by PabloSzx** [comment]
> you can already use `tsup.config.js`, it's just not documented.

😮 I didn't realize it before, is it possible to use a package.json field with joycon?

**Comment by harrytran998** [comment]
> > you can already use `tsup.config.js`, it's just not documented.
> 
> 😮 I didn't realize it before, ~is it possible to use a package.json field with joycon?~ I just read the docs and it does with "packageKey" field, would you agree on adding it as an option for the config and mentioning all this feature on the docs? I can work on the PR if you want

You should do that bro! For anyone who want to use it 🥰

**Comment by harrytran998** [comment]
@egoist You can take some time to review the PR of @PabloSzx and merge it 😊 ?
