### ISSUE TITLE
question: types have all the same icons in VS Code

### ISSUE THREAD

**Issue by alexanderniebuhr** [egoist/tsup#302]
not sure if that is something to fix in this lib, but it looks like packages using tsc for decleration files have better icon support in vs code. How to I get the same icons, functions have the `purble f`
3rd party lib form npm has
![image](https://user-images.githubusercontent.com/45965090/118251952-8099ca80-b4a8-11eb-9779-d8d19557638d.png)

my own lib using `tsup` to make declaration files (createRoutes is an function)
![image](https://user-images.githubusercontent.com/45965090/118252036-9c9d6c00-b4a8-11eb-83e2-59f1cf2634c3.png)

**Comment by OmgImAlexis** [comment]
@alexanderniebuhr I don't think this is what you're thinking.

The icons on the top look like they're corresponding with different things such as interfaces, functions, objects, variables, etc. whereas the bottom just looks like an object/function. What is the top package?

**Comment by alexanderniebuhr** [comment]
Top package is svelte/store.
I wonder how I get the icons, since on the bottom screenshot it is also a function

**Comment by egoist** [comment]
not sure how you get that

<img width="471" alt="CleanShot 2021-11-25 at 20 58 07@2x" src="https://user-images.githubusercontent.com/8784712/143445984-d68022f3-9304-4967-9c5c-cee6bf81edbf.png">
