### ISSUE TITLE
[Important] Package.json browser's shims are ignored

### ISSUE THREAD

**Issue by ConsoleTVs** [egoist/tsup#305]
See: https://esbuild.github.io/getting-started/#bundling-for-the-browser

Setting up a shim like this is ignored when using tsup while esbuild works fine.

**Comment by ConsoleTVs** [comment]
This is because: 

```
platform: 'node',
```

is sent to the esbuild build command.

More: https://esbuild.github.io/api/#platform

**Comment by ConsoleTVs** [comment]
Since the platform may differ depending on the output format and you can't determine the platform based on it (eg. esm can either be node or browser).

We may be able todo as follows:

```
--formats iffe:browser,esm:browser,cjs:node
```

**Comment by ConsoleTVs** [comment]
Alternatively, we can support the following options:

```
--prefer-browser
```

and determine the platform based format:

- Iffe: Browser
- Esm: Browser if --prefer-browser, Node otherwise
- Cjs: Node

**Comment by egoist** [comment]
For now use the `--platform browser` flag
