### ISSUE TITLE
feat: externalize package.json by default in tsup-node

### ISSUE THREAD

**Issue by privatenumber** [egoist/tsup#306]
While developing a CLI tool using semantic-release, I noticed the distributed version used `0.0.0-semantic-release` instead of the correct version because bundling was done prior to versioning the release.

I can fix this by putting the build in a prepublishOnly hook but I think it also makes sense for `tsup-node` to leave `package.json` externalized.

**Comment by egoist** [comment]
If you want the runtime value of `package.json` you can just `JSON.parse(fs.readFileSync('resolve/path/to/package.json', 'utf8'))`
