### ISSUE TITLE
[Bug] Tsup can not generate type correctly when source folder have 2 more classes

### ISSUE THREAD

**Issue by harrytran998** [egoist/tsup#307]
![image](https://user-images.githubusercontent.com/24296018/119228814-fd7b1300-bb3e-11eb-84d9-f718074f704a.png)
The `index.d.ts` do not add all types of all files!
I just work around this with tsup read-only entry point is `src/index.ts`
Hope you can clear this issue!

Link reproduce: https://github.com/harrytran998/tsup-bundler-rep/blob/main/dist/index.d.ts

**Comment by egoist** [comment]
hmm what's the actual / expected output?

**Comment by harrytran998** [comment]
Oops, I miss this reply 😔. 
If you `src` folder have some child folder --> The `index.d.ts` will generate only type for this folder.

In tsup config file: 

`entryPoints: ['src/index.ts', 'src/is.ts',` **'src/format/index.ts'**]

the `format` folder will only generate js file, and the index.d.ts will only contain the types of `format` folder.

Hope you clear that!

**Comment by OmgImAlexis** [comment]
I think the issue may come down to both of the entry points using `index` as their name. I'm guessing the last entry point is overriding the files from the first entry point. 

Have you tried named entry points like this? https://github.com/egoist/tsup/issues/447#issuecomment-953133287

**Comment by egoist** [comment]
This should be already fixed #316
