### ISSUE TITLE
[Enhancement] Sourcemap not generate index.d.ts.map file

### ISSUE THREAD

**Issue by harrytran998** [egoist/tsup#311]
It's really annoying when going to definition code when don't have the `index.d.ts.map` source map file! Hope anyone can do that!

**Comment by harrytran998** [comment]
:( OOps, thank you for the quick response! So I consider swap to Parcel to do that! You have any suggestions like Parcel?

**Comment by egoist** [comment]
hmm I don't think Parcel generates d.ts for you, maybe you should try rollup + rollup-plugin-typescript2

**Comment by harrytran998** [comment]
thank you <3! So I close it!
