### ISSUE TITLE
support specifying external with wildcard 

### ISSUE THREAD

**Issue by yaquawa** [egoist/tsup#325]
Can we get the ability to specify externals with wildcard?
esbuild allows specifying externals with wildcard:
https://esbuild.github.io/api/#external

**Comment by egoist** [comment]
You can directly pass esbuild options now:

```ts
// tsup.config.ts
export default {
  esbuildOptions(options) {
    options.external = ['some/*']
  }
}
```

Or just use tsup's external option with a RegExp:

```ts
export default {
  external: [/^foo\/.+$/]
}
```
