### ISSUE TITLE
How to use  path aliases

### ISSUE THREAD

**Issue by muco-rolle** [egoist/tsup#334]
I would like to use absolute path aliases but couldn't figure out how to set it up  with this project

I would like a path like this: 

```import { formatNumber } from "../../../utils"```

be like this: 

```import { formatNumber } from "@utils"```

**Comment by egoist** [comment]
using "paths" in `tsconfig.json` should work

**Comment by hampuskraft** [comment]
@egoist I get `Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@app/constants'` using tsup with path aliases. I'll gladly provide a reproducible example if necessary, but you can try it out with a minimal tsconfig.json, adding something like:

```json
  "compilerOptions": {
    "paths": {
      "@app/*": ["./src/*"]
    }
  }
  ```

**Comment by egoist** [comment]
@hampuskraft maybe you forgot `"baseUrl": "."` in `compilerOptions`.

**Comment by hampuskraft** [comment]
That gives the same result, since `baseUrl` isn't required for relative paths (see <https://github.com/microsoft/TypeScript/pull/40101>).

**Comment by egoist** [comment]
@hampuskraft yeah, a repro would be nice then, since I can't reproduce it locally

**Comment by hampuskraft** [comment]
@egoist Here's a repro, thanks! https://github.com/hampuskraft/tsup-paths

**Comment by egoist** [comment]
@hampuskraft I tried `npx tsup src/module-b.ts --clean --format esm --sourcemap --target esnext` and it works fine.

<img width="1019" alt="CleanShot 2021-09-16 at 23 29 19@2x" src="https://user-images.githubusercontent.com/8784712/133640871-ca70efc3-f313-4e9b-a318-5f9262565b71.png">

**Comment by egoist** [comment]
> @hampuskraft: Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@app/constants'

I guess this is an runtime error? seems to be related to https://github.com/egoist/tsup/issues/409

**Comment by egoist** [comment]
I'll close this and further updates will be added to #409.

**Comment by bhvngt** [comment]
Hi, it seems that path alias is not working for `tsup-node`. Since my module is targeted for node, I would prefer to not bundle them using `tsup`. Is there a workaround for this usecase?

**Comment by egoist** [comment]
@bhvngt does `tsup` work for you? it should exclude packages specified in `dependencies` by default

**Comment by bhvngt** [comment]
I have been using some of node's built-in packages and my project is following `esm` packaging standards with `type` set as `module`. This is generating a bundled up code which throws following error when I import my `library` from some other package.

```Error: Dynamic require of "fs" is not supported```.

**Comment by egoist** [comment]
@bhvngt a repo would be helpful

**Comment by bhvngt** [comment]
@egoist I have a created a repo [tsup-node-esm](https://github.com/bhvngt/tsup-node-esm) which replicates my issue. 

I have realised that if I move `tmp` package to `dependencies`, it all seems to work out fine. 

I do see that the code gets inlined during transpilation. Is there anyway to avoid that?

**Comment by CyberT33N** [comment]
Make sure to use a tsconfig file that include actually pathes. E.g. do not use the orchestrator tsconfig file with only referencernes. 

```ts
import { defineConfig } from 'tsup'

const config = defineConfig({
    clean: true,

    entry: {
        build: 'tooling/build/index.ts'
    },

  
    platform: 'node',

   
    format: ['esm'],


    target: 'node20',

  
    outDir: 'dist',

   
    dts: false,

 
    skipNodeModulesBundle: true,


    minify: false,
    splitting: false,

    sourcemap: false,
    treeshake: true,

    tsconfig: 'tsconfig.base.json'
})

```

**Comment by bovverCode** [comment]
Adding `"baseUrl": ".",` resolved my problem.

My configs, if someone is facing the issue:

```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "NodeNext",
    "moduleResolution": "NodeNext",
    "rootDir": "./src",
    "outDir": "./dist",

    "strict": true,
    "esModuleInterop": true,

    "types": ["node"],

    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "noUncheckedIndexedAccess": true
  }
}

/**
 * tsup configuration file.
 */
import { defineConfig } from 'tsup'

export default defineConfig({
    entry: ['src/**/*.ts'],
    format: ['esm'],
    outDir: 'dist',
})
```
