### ISSUE TITLE
dts file doesn't match `export = `

### ISSUE THREAD

**Issue by privatenumber** [egoist/tsup#338]
When using `export = ` with `--dts --no-splitting`, the declaration file uses `export default` instead of `export = `.

### Input
src/index.ts
```ts
function hello(name: string) {
	console.log(`Hello ${name}`);
}

export = hello;
```

package.json
```json
{
  "scripts": {
    "build": "tsup src/index.ts --dts --no-splitting"
  },
  "devDependencies": {
    "tsup": "^4.11.2",
    "typescript": "^4.3.4"
  }
}
```

tsconfig.json
```
{
	"compilerOptions": {
		"isolatedModules": true,
		"esModuleInterop": true,
		"declaration": true,
		"outDir": "dist",
		"module": "commonjs"
	},
	"include": [
		"src"
	]
}
```

### Output
dist/index.js
```js
// src/index.ts
function hello(name) {
  console.log(`Hello ${name}`);
}
module.exports = hello;
```

dist/index.d.ts
```ts
declare function hello(name: string): void;

export default hello; // should be export = hello
```

**Comment by privatenumber** [comment]
I think I spoke to soon actually.

I thought it had to be `export =` because that's what `tsc` outputs, but seems Typescript handles this fine when importing it.

**Comment by privatenumber** [comment]
I'm noticing intellisense doesn't actually work when importing the module via CJS require.

But since it's TypeScript, I guess it's reasonable to expect all imports would be ESM import.

Would still be nice to have it be `export =` for correctness and Intellisense but no longer a blocker for me. Feel free to re-open.

**Comment by egoist** [comment]
rollup-plugin-dts doesn't support `export = ` pattern If I recall correctly.
