### ISSUE TITLE
release tsup with updated esbuild

### ISSUE THREAD

**Issue by PabloSzx** [egoist/tsup#339]
@egoist the esbuild version was already updated https://github.com/egoist/tsup/commit/3f69964df2c8c62443a9636b8f4141507a7421b6, but tsup hasn't been released with the update yet

**Comment by egoist** [comment]
Now released https://github.com/egoist/tsup/releases/tag/v4.12.0

**Comment by PabloSzx** [comment]
Thank you 👌
