### ISSUE TITLE
bundle config file killed docs suggestion of using "export const tsup"

### ISSUE THREAD

**Issue by PabloSzx** [egoist/tsup#351]
as seen in the commit https://github.com/egoist/tsup/commit/7d03efeb5453b0a30781b2ae0b0735cf4d66abe4#diff-51cd61f2399d311debdd2c813260b4a799b0cd6155b8eaa0f1498aebdc5ca281

that kills the syntax `export const tsup` https://tsup.egoist.sh/#typescript since you removed `if (config.data && config.data.tsup) config.data = config.data.tsup` @egoist 

checking the "tsup" property shouldn't be "package.json" exclusive

**Comment by egoist** [comment]
Ahh I didn't notice that

**Comment by egoist** [comment]
Actually here's an alternative way to get doc suggestion when using default export:

```ts
import { defineConfig } from "tsup"

export default defineConfig({
  entryPoints: ["foo.js"],
})
```

**Comment by PabloSzx** [comment]
I agree that looks cleaner,  and thanks for fixing the issue  🎉
