### ISSUE TITLE
Ambient d.ts

### ISSUE THREAD

**Issue by PuruVJ** [egoist/tsup#361]
Hi I have an ambient `d.ts` file in my `src` folder. Problem is that the output file isn't including the contents of the ambient d.ts. How can I make sure the ambient d.ts is inlined into the output d.ts?

My tsup config

```ts
import { defineConfig } from "tsup";

export default defineConfig({
  sourcemap: true,
  clean: true,
  dts: true,
  format: ["esm"],
  entryPoints: ["src/index.ts"],
  minify: false,

  target: "es2018",
});

```

Directory structure
![image](https://user-images.githubusercontent.com/47742487/126076811-93a0eb75-f816-4b66-8d23-b5442b9e1c88.png)

Thanks

**Comment by PuruVJ** [comment]
Is there some alternate solution to this? Should I try something other than tsup for the types? If so, pls suggest these methods 🙏

**Comment by PuruVJ** [comment]
Is it not possible in TSUP yet? Or even in TSC?

**Comment by PabloSzx** [comment]
@PuruVJ dts-bundle-generator https://github.com/timocov/dts-bundle-generator does a more in-depth work into this, and what you mention should work using it

**Comment by egoist** [comment]
An alternative way is to manually adding your ambient d.ts to the generated d.ts files via triple-slash reference, I wonder if tsup should support this by default.

**Comment by egoist** [comment]
With v5.10.0 you can manully add a banner to your .d.ts output:

```ts
export default {
  dts: {
    banner: `/// <reference path="../types/some.d.ts" />`
  }
}
```

**Comment by PuruVJ** [comment]
Damn!!! Thanks for this
