### ISSUE TITLE
support loading config from a parent folder (monorepo)

### ISSUE THREAD

**Issue by jcayzac** [egoist/tsup#378]
Hi @egoist!

My project structure has:

```
+-- project
    +-- packages
    |   +-- library
    +-- tsup.config.ts
```

When I call `tsup` from the `library` folder, it fails to find the config file. I see you're setting joycon's `stopDir` to the current project's folder:

https://github.com/egoist/tsup/blob/405e165ef7412adf54b9a83248144daa4c13be04/src/load.ts#L44-L55

Would you have any objection to changing that and allow `resolve()` to traverse the filesystem upward?

```diff
export async function loadTsupConfig(cwd: string) {
  const configJoycon = new JoyCon()
  const configPath = await configJoycon.resolve(
    [
      'tsup.config.ts',
      'tsup.config.js',
      'tsup.config.cjs',
      'tsup.config.mjs',
      'tsup.config.json',
      'package.json',
    ],
-   cwd,
-   path.dirname(cwd)
+   cwd
  )
```

Thanks!

**Comment by jcayzac** [comment]
Basically this would spare me having to write dummy one-line `tsup.config.ts` files in each of my packages, with just `export { tsup } from '../../tsup.config'.

**Comment by xiaoyu-tamu** [comment]
does this still work in 5.12.1?

`No input files, try "tsup <your-file>" instead`

```
+-- project
    +-- packages
    |   +-- library
    +-- tsup.config.ts
```

**Comment by schelmo** [comment]
no it isnt for me too.
i think the code in  https://github.com/egoist/tsup/blob/b8c51f45532f3c0da8d2b6a3c582f30ec3cfe24c/src/load.ts#L39-L50
should first check for `tsup.config.{ts,js,cjs,mjs,ts,json} `
and after that, check for package.json
so if there is a tsup.config.ts in workspace root, take that, else check for package.json
