### ISSUE TITLE
how to mark some package form node_modules as internal ?

### ISSUE THREAD

**Issue by wensonsmith** [egoist/tsup#389]
by default dependencies and peerDependencies in your packages.json are always excluded, how can i include some package from dependencies and peerDependencies?

**Comment by egoist** [comment]
why would you want to bundle a package that is already a dependency?

Wenson Smith ***@***.***>于2021年8月17日 周二下午11:39写道：

**Comment by wensonsmith** [comment]
I use [antfu/vitesse-webext](https://github.com/antfu/vitesse-webext) template to build a web extension now . 

it use tsup to bundle content scripts, which will insert into the web . 

in content scripts , i need [dayjs](https://day.js.org/) to parse & format datetime,  dayjs is in dependencies, so tsup didn't bundle it by default, and content script will report an error that can not find dayjs 

i just remove dayjs from dependencies , it works .   here is the scenario。

**Comment by wensonsmith** [comment]
Demo: https://stackblitz.com/edit/node-rwrubu?file=index.ts

**Comment by egoist** [comment]
Added a new option `noExternal: Array<string | RegExp>` in v5.10.0 for this

**Comment by frontendtony** [comment]
@egoist Thank you for this library and this little extra config option that just saved me from what would've been days of trying to learn how to build a rollup plugin 🙏🏽

**Comment by dhowe** [comment]
Curious if it possible to use `noExternal` for one of my output formats, but not the other?
