### ISSUE TITLE
support moving static assets to dist and support importing reference altering

### ISSUE THREAD

**Issue by zheeeng** [egoist/tsup#392]
Can we easily use it for bundling browser-oriented lib for distribution? It is useful to feed js and assets to application bundlers like webpack/rollup/vite

**Comment by egoist** [comment]
You can import static assets now.

**Comment by ScreamZ** [comment]
@egoist Hello, how ? Not documented yet seems

**Comment by whoisryosuke** [comment]
Better documentation for this would be great, it's not very clear what works out of the box, or how to configure output (like customizing the asset URL to a different root/base path).

**Comment by ugnelis** [comment]
For creating assets folder and loading assets via file:

```typescript
import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.tsx'],
  dts: true,
  external: ['react'],
  format: ['cjs'],
  esbuildOptions(options, context) {
    options.assetNames = 'assets/[name]';
  },
  loader: {
    '.svg': 'file',
  },
});
```

Foading assets via `dataurl`:

```typescript
import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.tsx'],
  dts: true,
  external: ['react'],
  format: ['cjs'],
  loader: {
    '.svg': 'dataurl',
  },
});
```
