### ISSUE TITLE
Doesn't add declare to enums

### ISSUE THREAD

**Issue by ghostdevv** [egoist/tsup#400]
I just started using enums and I noticed when shipping a new version of my package that tsup is creating a incorrect dts. Sometimes `declare` is not added in front of a enum. I am not sure why this is happening so I linked a demo below:

<https://github.com/ghostdevv/tsup-enum-repro>

**Comment by egoist** [comment]
dts generation is handled by rollup-plugin-dts so nothing we can do here.

**Comment by ghostdevv** [comment]
Will make an issue there
