### ISSUE TITLE
`tsup-node` should not mark module alias as external

### ISSUE THREAD

**Issue by egoist** [egoist/tsup#409]
If you have a path alias like `@app/*` configured in `tsconfig.json` and run `tsup-node` against your files, `@app`  will be accidentally marked as external, it needs to be fixed here:

https://github.com/egoist/tsup/blob/6075c803126390eb5660b26419c6aea57bcf8763/src/esbuild/external.ts#L17-L22

**Comment by egoist** [comment]
Fow now just use `tsup`.

**Comment by br0p0p** [comment]
Hi, I'm using Yarn's `link:` protocol for aliasing and `tsup` is including it as an external.

for example in my `package.json` I have:

```json
"dependencies": {
	"~src": "link:./src"
}
```

and `~src` is being marked as external in the build config. 

The solution is probably to either handle this case specifically by filtering out dependencies that use the `link:` protocol from the `external` list or remove aliases determined from `tsconfig`'s `paths` from the `external` list.

**Comment by egoist** [comment]
if you don't want to make it external you should move it to
`devDependencies`

Caleb Williams ***@***.***>于2021年11月24日 周三上午1:13写道：

**Comment by br0p0p** [comment]
@egoist I'm already using `tsup` (not `tsup-node`) but I'll move the alias to `devDependencies` 👍
