### ISSUE TITLE
Exclude certain files from bundling

### ISSUE THREAD

**Issue by faustbrian** [egoist/tsup#415]
Hey, is it possible to exclude certain files from the bundling process? Couldn't find any configuration but maybe I'm overlooking it.

My use-case would be to ignore all `source/**/*.test.ts` files when bundling as they are currently included in the tarball for the npm registry.

**Comment by egoist** [comment]
You can use the `external` option: https://github.com/egoist/tsup/blob/71ad251014346c8e5ce47729cb27d8f63b79ee9d/src/options.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L54
