### ISSUE TITLE
Support resolving `node:` protocol, i.e. `node:fs/promises`

### ISSUE THREAD

**Issue by arabold** [egoist/tsup#417]
First of all, let me thank you for `tsup`. I tried several bundlers and it's just a PITA getting a supposedly simple TypeScript cli to work without spending hours configuring things. `tsup` worked nearly instantly. It only threw up for one little issue... Hence this feature request.

I'm using [xo](https://github.com/xojs/xo) to simplify my ESLint setup. It comes with a bunch of opinionated linter rules. The one that is relevant here is:
* [unicorn/prefer-node-protocol](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md)

By enabling this rule (which is the default in `xo`), you'll have to prefix the import of built-in modules with `node:`. For example, if you want to access `fs` you have to import it like this:

```
import fs from 'node:fs/promises'
```

I don't want to argue whether this is a good or bad idea, I personally have never even seen this before yesterday, but apparently it is documented in the [Node v16 ESM specs itself](https://nodejs.org/api/esm.html#esm_node_imports). `tsup` doesn't seem to handle the `node:` prefix properly though. It throws an error `Cannot find module 'node:fs/promises'`. For now, I've simply disabled the `unicorn/prefer-node-protocol` rule and use built-in modules as I always used to.

Would that be something that can be added to `tsup` easily? My understanding is that anything that's using the `node:` protocol can simply be treated like any other modules by stripping the `node:` prefix. There are also `file:` and `data:` protocols, but I'm not sure if and how those could be handled best. Adding `node:` would be a good start though.

**Comment by egoist** [comment]
what's the command you ran? it doesn't throw the error for me

**Comment by arabold** [comment]
I think I found my mistake. I was using Node 14 and somehow expected `tsup` to strip the `node:` protocol prefix when transpiling my TypeScript sources. But the `node:` protocol a Node 16 feature and if I use Node 16 it also works as expected.

Sorry for the confusion. I think we can close this.
