### ISSUE TITLE
Output name?

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#447]
Is there a way to set the output name?

I'm trying to bundle a few different entry points and they're all using `index.ts` so I was hoping to have an option like `--name my-bundle` which would result in `dist/my-bundle.js`

This would likely effect `metafile` as it'd need to be changed from `metafile-{format}.json` to `metafile-{name}-{format}.json`

**Comment by OmgImAlexis** [comment]
Duplicate of https://github.com/egoist/tsup/issues/214

**Comment by NotoriousPyro** [comment]
If you're like me and transpiling from `ts` to `js` and don't care about changing file names, this is another solution.

This will store the `.js` files alongside the `.ts` files:
```tsup _devServer.ts types/my-other-file.ts --out-dir ./ --format cjs --target node16 --watch --onSuccess \"node _devServer.js\"```

Then you will get:
```
_devServer.js
_devServer.ts
types/my-other-file.js
types/my-other-file.ts
```

Alternatively you can create a package and export all you need into one `index.ts` :
```json
{
    "name": "my-package",
    "type": "commonjs",
    "private": true,
    "version": "1.0.0",
    "description": "",
    "main": "./dist/index.js",
    "types": "./dist/index.d.ts",
    "files": [
        "dist/"
    ],
    "scripts": {
        "build": "tsup src/index.ts --dts",
        "dev": "npm run build --watch",
        "lint": "npx eslint . --ext .ts",
    },
    "keywords": [],
    "author": "",
    "license": "ISC"
}
```

```typescript
export {
    stuff
} from './my-stuff'
export * from './types'
```

Then in the output you will find all of the things you exported.

**Comment by SonNg2k** [comment]
Hello @egoist , do you know how to change the names of the output file from `app.ts` to outCustomName.js like below:

```
import { defineConfig, type Options } from 'tsup';

export default defineConfig((options: Options) => ({
  entry: ['src/templates/customers/*/app.ts'], // files should be named as "*.js" in the ./build folder
  noExternal: [/^@amest\//],
  clean: true,
  format: 'esm',
  shims: true,
  outDir: 'build',
  treeshake: true,
  ...options,
}));

```
