### ISSUE TITLE
Support banner and footer esbuild options?

### ISSUE THREAD

**Issue by iCrawl** [egoist/tsup#451]
https://esbuild.github.io/api/#banner
https://esbuild.github.io/api/#footer

Not sure if there's a nice way to dynamically forward any kind of options esbuild supports so this doesn't have to be updated all the time.

Use case: https://github.com/evanw/esbuild/issues/946#issuecomment-814703190

**Comment by egoist** [comment]
You can use a esbuild plugin to modify build options: https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

and pass the plugin to `tsup.config.ts`:

```ts
import type { Options } from 'tsup'

export const tsup: Options = {
  esbuildPlugins: [yourPlugin]
}
```

**Comment by egoist** [comment]
Now you can directly use `footer` and `banner` options in `tsup.config.ts`

**Comment by loynoir** [comment]
Just a notice for new searchers come in.

A bit different from esbuild.

https://github.com/egoist/tsup/discussions/505
```js
topLevelCreateRequire(import\.meta.url)
```
result in
```js
topLevelCreateRequire(import.meta.url)
```

https://github.com/evanw/esbuild/issues/946#issuecomment-814703190

```js
topLevelCreateRequire(import.meta.url)
```
result in
```js
topLevelCreateRequire("file:///path/to/tsup.config.ts")
```

**Comment by loynoir** [comment]
@egoist 
I think instead of
```js
topLevelCreateRequire("file:///path/to/tsup.config.ts")
```
should be rewritten to
```js
topLevelCreateRequire("file:///path/to/package.json")
```
