### ISSUE TITLE
Watch not detecting when files change due to git

### ISSUE THREAD

**Issue by vpontis** [egoist/tsup#478]
So I'm trying to get `tsup` to recompile a directory when I change any of the files in the editor *or* when I checkout a different git branch. 

Somehow this isn't working, here's an example:

![CleanShot 2021-12-01 at 19 19 35](https://user-images.githubusercontent.com/1319079/144335147-422b48db-ba45-4a0a-8d32-8d99b304888a.gif)

I think this may be a Rollup watch issue.

Anyone have any ideas on how to fix this?

**Comment by vpontis** [comment]
Btw this is on MacOS Monterey 12.0.1 and I tested Chokidar and it works fine... So it must be either Rollup or the connection of Rollup and tsup.

**Comment by egoist** [comment]
It will only re-build after the files you imported have changed

**Comment by vpontis** [comment]
OK I think I was doing a couple things wrong. 

1. I was expecting `--watch` to pick up everything properly but doing `--watch src/` seems to fix it for me. 
2. I was expecting `--watch ../.git/HEAD` to work but I don't think it works since `.git` is also ignored.
