### ISSUE TITLE
[Wanted] Support inject style

### ISSUE THREAD

**Issue by zhmushan** [egoist/tsup#479]

**Comment by egoist** [comment]
that's nice to have, but I'm not sure how to implement this

**Comment by egoist** [comment]
If you load css as a js module `export default styleInject("..css code")` then you can't take advantage of esbuild to minify the CSS cde.

**Comment by egoist** [comment]
just realized we can use `esbuild.transform` to minify the CSS code on demand, so maybe that'll work.
