### ISSUE TITLE
Legal Comments Not Preserved

### ISSUE THREAD

**Issue by BeeeQueue** [egoist/tsup#480]
It seems like legal comments are not preserved, no matter what `esbuildOptions.legalComments` is set to.

I also double checked that `tsconfig.json`'s `removeComments` is set to false

**Comment by BeeeQueue** [comment]
It might be because my modules aren't being bundled like I want them to...

Is there a way to still bundle imports with `platform: "node"`? `external` and `noExternal` isn't doing anything for me.

**Comment by egoist** [comment]
imports should always be bundled unless it's node_modules

**Comment by BeeeQueue** [comment]
Is there any way to bundle something from `node_modules` using options, or is that out of scope?

**Comment by egoist** [comment]
> Is there any way to bundle something from `node_modules` using options, or is that out of scope?

devDependencies will also be bundled, see https://tsup.egoist.sh/#excluding-packages
