### ISSUE TITLE
Run typescript code and restart on changes

### ISSUE THREAD

**Issue by maximkott** [egoist/tsup#482]
Tsup has been really amazing so far. I would love if it could become a one stop solution for all typescript related build needs. As of now, you still need to use something like `ts-node-dev` to run your code from an entry point and restart on changes.

What is the vision of tsup, is it feasible to add support for something like this? Most of the functionality is already available, the only thing that's missing - is a way to run an entry point and to restart it whenever some of the watched files change?

I would be happy to contribute on this feature, not sure if it aligns with the team's "vision" and is not "out of scope".

Thanks for the amazing lib, the type bundling functionality is incredible. It's my go to tool for all typescript related build processes.

**Comment by PabloSzx** [comment]
There is the --onSuccess & --watch

https://tsup.egoist.sh/#onsuccess

https://tsup.egoist.sh/#watch-mode

**Comment by maximkott** [comment]
@PabloSzx Cool, thank you for the hint! It wasn't obvious for me / didn't realise that's the option that I need. Maybe the naming could be improved?

At least the next person with the same issue will find this ticket and also a solution 🙂 

Feel free to close this one.

**Comment by darklight9811** [comment]
Just a comment @egoist, maybe it could be interesting to display this as a feature within documentation/readme. Like an example of what you can do with tsup
