### ISSUE TITLE
how to use emitDecoratorMetadata with path aliases

### ISSUE THREAD

**Issue by zLupa** [egoist/tsup#484]
I'm trying to build an application that uses `reflect-metadata` and for some reason when I install `@swc/core` to emit the metadata as described in this issue comment https://github.com/egoist/tsup/issues/298#issuecomment-979275213 the path aliases stop working.
![image](https://user-images.githubusercontent.com/56929033/144911044-b7a62cf7-b79b-442d-9a48-6bf1d19fc1b3.png)
![image](https://user-images.githubusercontent.com/56929033/144911240-17a070a2-2385-427d-94ce-2c14d04d0a3a.png)

Command being used: `yarn tsup src/`

**Comment by zLupa** [comment]
It's an issue with `@swc/core` https://github.com/swc-project/swc/issues/2753.
It doesn't translate path-aliases if the module isn't `commonjs` and also tsup doesn't seem to provide the paths and the baseUrl in the JscConfig https://github.com/egoist/tsup/commit/531a05eeda98d659519842d43fab96de639e653c#diff-9290f26e7bf7a9fe9720ea49c795b8f292c16efd2093925f68af2aa9bd411b2fR25

I can probably open a PR to solve the tsup part if you guys want.

**Comment by egoist** [comment]
that's weird because path alias should still be handled by esbuild

**Comment by zLupa** [comment]
> ~that's weird because path alias should still be handled by esbuild~ oh it seems to happen during the build

Yep, it's happening when I'm building it

**Comment by egoist** [comment]
does `import type { IUserRepository } from '...'` work? it seems to an interface which gets removed after swc transformation.

**Comment by zLupa** [comment]
> does `import type { IUserRepository } from '...'` work? it seems to an interface which gets removed after swc transformation.

Yes, now it works.
![image](https://user-images.githubusercontent.com/56929033/145288052-923eacad-84e5-4906-b385-14423b6c54b0.png)

**Comment by zLupa** [comment]
After a looking, just seems to be happening with types only so import type should resolve, and also I couldn't find a way in `@swc/core` to include the types only in the final build.

**Comment by daolou** [comment]
entry is:
```
export * from '@/dom';
export * from '@/eval';
export { obj2str } from '@/object';
export * from '@/schema';
export * from '@/typedef';
```
tsup.config is:
```
defineConfig([
  {
    ...commonConfig,
    entry: ['src/**/*.ts'],
    splitting: true,
    target: 'es5',
    format: 'cjs',
    dts: true,
    treeshake: true,
    bundle: false,
  }
]);
```

in above case, paths(alias) seem not work
