### ISSUE TITLE
Option `sourcemap: 'inline'` not working

### ISSUE THREAD

**Issue by fox1t** [egoist/tsup#495]
Hi!
As per [documentation](https://tsup.egoist.sh/#generate-sourcemap-file) it should be possible to pass `inline` as `sourcemap` option. In reality, passing it is treated the same as passing any other value thanks to this line: https://github.com/egoist/tsup/blob/dev/src/esbuild/index.ts#L134

Moreover, the relative test is wrong too and doesn't catch this error. We can see that it is checking for the presence of 
at https://github.com/egoist/tsup/blob/dev/test/index.test.ts#L188 instead of the more safe `//# sourceMappingURL=data:`

I've already had a fix, and I can open a PR, but there is just one last thing that bothers me. `esbuild` [documentation](https://esbuild.github.io/api/#sourcemap) says that `external` shouldn't add `//# sourceMappingURL=` at the end of the file, but running [this test ](https://github.com/egoist/tsup/blob/dev/test/index.test.ts#L165) and checking the output, shows a different story. Any clues?

And this is why the `inline` test is passing even if the option is not working at the moment.

```
...
PERFORMANCE OF THIS SOFTWARE.
***************************************************************************** */
//# sourceMappingURL=input.js.map
```

**Comment by egoist** [comment]
inline sourcemap was removed and the docs should be updated, any specific reason you need inline sourcemap?

**Comment by fox1t** [comment]
I am developing a custom tsup configuration that takes some paramters that tsup care about directly from the tsconfig.json. 
In particular:
- entry is mapped to tsConfig.fileNames
- outDir is tsConfig.outDir
- sourcemap: is either tsConfig.sourcemap or tsConfig.inlineSourceMap
- target is tsConfig.compilerOptions.target

Should we remove the `inline` option test too?

**Comment by egoist** [comment]
just did a bit research, there're indeed use cases for inline sourcemap (like developing browser extensions), we should bring it back, but it should be added in https://github.com/egoist/tsup/blob/d428ce7be1341fe7c8d6f745eaa0676f9eeeea89/src/plugin.ts#L160-174, currently we perform some extra operations on the sourcemap output by esbuild and manually write it to disk
