### ISSUE TITLE
Tsup doesn't accurately collect tsconfig.json preferences

### ISSUE THREAD

**Issue by Lioness100** [egoist/tsup#524]
After some testing, it looks like tsup doesn't resolve tsconfig extensions. For example, if my tsconfig was:
```json
{
	"extends": "../tsconfig.base.json",
	"compilerOptions": {
		"baseUrl": "."
	}
}
```
And `../tsconfig.base.json` was:
```json
{
	"compilerOptions": {
		"emitDecoratorMetadata": true
		...
	}
}
```

Tsup wouldn't detect any of the extended options, such as `emitDecoratorMetadata`. This seems to be because you only read the file through `fs.readFileSync` and use the results directly. However, I believe you need to use typescript's compiler API to get the full contents. Something like this:
```ts
const parsedTsConfig = typescript.parseJsonConfigFileContent(tsconfig, typescript.sys, outDir);
```
You can find a good example of that [here](https://github.com/anatine/esbuildnx/blob/2a08d48e3873e5de0cfbdc518e75f6ebca7f0c1d/packages/esbuild-decorators/src/lib/esbuild-decorators.ts#L87-L116), and I could also probably make PR if needed.

**Comment by Lioness100** [comment]
My tsconfig:

```json
{
	"extends": "../tsconfig.base.json",
	"compilerOptions": {
		"outDir": "../dist",
		"rootDir": ".",
		"baseUrl": ".",
		"noEmit": true,
		"paths": {
			"#root/*": ["*"],
			"#lib/*": ["lib/*"],
			"#types/*": ["lib/types/*"],
			"#structures/*": ["lib/structures/*"],
			"#utils/*": ["lib/utils/*"],
			"#database/*": ["lib/database/*"]
		}
	},
	"include": ["."]
}
```

The extended tsconfig has `emitDecoratorMetadata`

Logs: 
![image](https://user-images.githubusercontent.com/65814829/147698171-31b05cd0-6f55-4949-89b9-709cd25cb77e.png)

**Comment by Lioness100** [comment]
Furthermore, if there isn't one already, might I suggest an option to manually disable the swc plugin? This would be useful if:
- The option was included in an external tsconfig you're extending, but you're not actively making use of it
- You'd like to create your own implementation of the plugin, either not using swc, or being selective with the files that get transformed with it (maybe only an `entities` directory if using typeorm, or creating a regex to search for decorators)

**Comment by Lioness100** [comment]
Furthermore, if there isn't one already, might I suggest an option to manually disable the swc plugin? This would be useful if:
- The option was included in an external tsconfig you're extending, but you're not actively making use of it
- You'd like to create your own implementation of the plugin, either not using swc, or being selective with the files that get transformed with it (maybe only an `entities` directory if using typeorm, or creating a regex to search for decorators)

**Comment by Lioness100** [comment]
Should I just submit a PR to the package that reads the tsconfig?

**Comment by egoist** [comment]
I'd like to use a library that doesn't use the `typescript` compiler to load tsconfig.json, since tsup should work without `typescript`

**Comment by Lioness100** [comment]
What if, in this library, once and if the raw tsconfig data is collected, the code checks if  typescript is installed, uses it to expand the tsconfig if it is, and just keeps the original otherwise?

**Comment by cenk1cenk2** [comment]
Maybe this one would fit the bill in the sense of not using Typescript.

https://www.npmjs.com/package/tsconfig-loader

**Comment by Lioness100** [comment]
Oooh that looks perfect!

**Comment by egoist** [comment]
This should be fixed in 5.11.12, please give it a try 

btw I made a package for this: https://github.com/egoist/load-tsconfig (even more light-weight than tsconfig-loader)

**Comment by Lioness100** [comment]
Great, thank you so much! Can I also make a PR that adds the option to force tsup to use esbuild over swc, even if the emitDecoratorMetadata is enabled somewhere?

**Comment by wojtekKrol** [comment]
@egoist why when i install this as devdeps it's not recognized?
`TS2307: Cannot find module  load-tsconfig  or its corresponding type declarations.`
