### ISSUE TITLE
[bug]generate dts bundle rename type using declare const

### ISSUE THREAD

**Issue by skimmilk6877** [egoist/tsup#544]
reproduce repo：https://github.com/skimmilk6877/tsup-bugs-1

declare namespace WebGradients {
  export {
    WebGradients_Key as Key,
  };
}

declare const _api$3_Colors: typeof Colors;    // wrong line
declare const _api$3_BoxShadow: typeof BoxShadow;
declare const _api$3_WebGradients: typeof WebGradients;
declare namespace _api$3 {
  export {
    _api$3_Colors as Colors,
    _api$3_BoxShadow as BoxShadow,
    _api$3_WebGradients as WebGradients,
  };
}

**Comment by egoist** [comment]
Please report this to the upstream repo: rollup-plugin-dts.
