### ISSUE TITLE
Error with GraphQL

### ISSUE THREAD

**Issue by ragokan** [egoist/tsup#548]
Hello, I am having an error while building/running with *tsup* but I don't receive this error with *ts-node* or *ts-node-dev*.

The error is;
```
NoExplicitTypeError: Unable to infer GraphQL type from TypeScript reflection system. You need to provide explicit type for argument named 'where' of 'getTodos' of 'TodoResolver' class.
    at Object.findType (/Users/ragokan/Projects/servers/g-server/node_modules/.pnpm/type-graphql@1.1.1_08bb4bc35f71ac150d0c5ea426cb8635/node_modules/type-graphql/dist/helpers/findType.js:19:15)
    at Object.getParamInfo (/Users/ragokan/Projects/servers/g-server/node_modules/.pnpm/type-graphql@1.1.1_08bb4bc35f71ac150d0c5ea426cb8635/node_modules/type-graphql/dist/helpers/params.js:10:49)
    at /Users/ragokan/Projects/servers/g-server/node_modules/.pnpm/type-graphql@1.1.1_08bb4bc35f71ac150d0c5ea426cb8635/node_modules/type-graphql/dist/decorators/Arg.js:14:25
    at _dec1 (/Users/ragokan/Projects/servers/g-server/dist/index.js:9646:5)
    at /Users/ragokan/Projects/servers/g-server/dist/index.js:9601:24
    at Array.reduce (<anonymous>)
    at _applyDecoratedDescriptor (/Users/ragokan/Projects/servers/g-server/dist/index.js:9600:39)
    at Object.<anonymous> (/Users/ragokan/Projects/servers/g-server/dist/index.js:9649:5)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
 ```

    
  In this package, I am using *type-graphql*, *reflect-metadata*, *prisma* and *apollo-server*.

**Comment by egoist** [comment]
Please provide a minimal repro.

**Comment by ragokan** [comment]
> Please provide a minimal repro.

Hello, I found the problem. I load the typedefs just like this 
`typeDefs: loadFilesSync(join(__dirname, "./post.schema.graphql")),`

But weirdly tsup does not build these graphql files, how can I make it build graphql files without changing? With loaders it compiles them into JS or etc.

**Comment by egoist** [comment]
only files imported with `import` or `require()` can be built by tsup, you can configure `loader` to load `.graphql` as raw text instead: https://tsup.egoist.sh/#custom-loader

**Comment by ragokan** [comment]
> only files imported with `import` or `require()` will be bundled by tsup, you can configure `loader` to load `.graphql` as raw text instead: https://tsup.egoist.sh/#custom-loader

But when I do it, it creates `*.js` files which disables the features. How can I do just what css does?

**Comment by ragokan** [comment]
> only files imported with `import` or `require()` will be bundled by tsup, you can configure `loader` to load `.graphql` as raw text instead: https://tsup.egoist.sh/#custom-loader

Also when I import graphql files manually it compiles them to:
```js
// src/modules/bank/schemas/bankAccount.graphql
var bankAccount_default = "./bankAccount-U44C4PZJ.graphql";
```
Because it does not use *require*, they are never read. When I do *raw text*, it sadly can't read it.

**Comment by ragokan** [comment]
> only files imported with `import` or `require()` will be bundled by tsup, you can configure `loader` to load `.graphql` as raw text instead: https://tsup.egoist.sh/#custom-loader

Sorry to ask again, is there any info that you can give me?

**Comment by egoist** [comment]
Using a flag like `--loader ".graphql=text"` and:

```js
import schema from './your-schema.graphql`

typeDefs: schema
```

**Comment by ragokan** [comment]
> Using a flag like `--loader ".graphql=text"` and:
> 
> ```js
> import schema from './your-schema.graphql'
> 
> typeDefs: schema
> ```


Hey, it did not work directly but when I did  `typeDefs: gql schema` it worked. Thanks but I hope there will be a dynamic way to use in future, like load files sync.
