### ISSUE TITLE
CACError: Unknown option `--clean`

### ISSUE THREAD

**Issue by OmgImAlexis** [egoist/tsup#559]
Is `--clean` not a cli flag? There's a top level field in the options for it so I had assumed it was also a flag?

**Comment by egoist** [comment]
It's a cli flag, I can't reproduce this error.

**Comment by OmgImAlexis** [comment]
This is the exact command I used.

```
tsup src/index.ts --format esm,cjs,iife --legacy-output --dts --clean
```

```
    "tsup": "^3.12.1",
    "typescript": "^4.4.3"
```

**Comment by egoist** [comment]
Try to upgrade tsup 😬
