### ISSUE TITLE
Feature Request: Logging Levels

### ISSUE THREAD

**Issue by cenk1cenk2** [egoist/tsup#560]
hey @egoist ,

and thank you again for introducing this beautiful project.

Is there a possibility to add logging levels for the CLI? 

So the problem that I have is whenever I use a regular expression to keep the folder structure the same as in the configuration: 

```typescript
import { defineConfig } from 'tsup'

export default defineConfig((options) => ({
  name: !options.watch && 'production',

  entry: ['src/**/*.{js,ts}'],
  tsconfig: options.watch ? 'tsconfig.json' : 'tsconfig.build.json',

  dts: true,

  format: ['cjs'],

  target: ['es2021'],

  sourcemap: options.watch && true,

  splitting: false,
  clean: true,
  minify: false,

  onSuccess: 'yarn run postbuild'
}))
```

Whenever I am using watch mode I get all the files listed again as compiled. Is there a way to just list the files that should be re-compiled in the watch mode with some kind of log-level implementation?

This is not much of a problem in production mode because it only runs once. But considering I am using the watch mode in a mono repo with 20 packages, I miss out on some errors from them with extensive output that is shown.

I would like to kindly ask you whether you consider this feature and whether I can help you with that if you show me some guidance on how you would have done it.

**Comment by egoist** [comment]
There's a `--silent` flag that suppresses anything but error logs

**Comment by StarpTech** [comment]
Hi, when I add `silent: true` I get an error.

```ts
await build({
		entry: entryPoints,
		outDir: generatedBundleDir,
		skipNodeModulesBundle: true,
		silent: true,
		platform: 'node',
		minify: true,
		clean: true,
		bundle: true,
		target: 'esnext',
	});
```

Error

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

After I remove it, it works again :smile: 

TsUp: 6.2.2

**Comment by meotimdihia** [comment]
@egoist How about I want to see "warning" logs?
