### ISSUE TITLE
Why do I get this error after compiling and trying to run the code?

### ISSUE THREAD

**Issue by ChikoShidori** [egoist/tsup#581]
![image](https://user-images.githubusercontent.com/53100578/156904761-2d9756ce-975e-469f-934b-ee83de9d8600.png)

I don't have any file with that name and I haven't found anything in the node modules.

**Comment by OmgImAlexis** [comment]
What's your `yarn start` command?

**Comment by ChikoShidori** [comment]
Nvm, I think I found the error.
