### ISSUE TITLE
Feature request:  add tsup-run command

### ISSUE THREAD

**Issue by jlarmstrongiv** [egoist/tsup#582]
tsup is a great bundler!  While it may take some finagling, I was able to get all of my code to build with tsup—no small feat.

Other tools, like ts-node and more, are unable to play nicely with esm like tsup does.  Plus, tsup already has all the polyfills and other options I need.

I would love a `tsup-run` so that I can just use tsup for everything, including one-off scripts.

**Comment by egoist** [comment]
For now, `tsup src/index.ts --onSuccess "node dist/index.js"` is pretty much `tsup-run src/index.ts`

**Comment by jlarmstrongiv** [comment]
@egoist wow

**Comment by jlarmstrongiv** [comment]
For reusability, I wrapped it in a shell script:

```bash
#!/usr/bin/env bash

# pattern matching https://reactgo.com/bash-check-string-ends-with-other/
# elif https://www.tutorialkart.com/bash-shell-scripting/bash-else-if/
# prefix https://stackoverflow.com/a/16623897
# suffix https://stackoverflow.com/a/61294531
# tsup-run https://github.com/egoist/tsup/issues/582
# exit https://unix.stackexchange.com/questions/308207/exit-code-at-the-end-of-a-bash-script

filename=${1#.\/}
if [[ "$1" == *ts ]]; then
    filename="${filename%.ts}"
    npx tsup-node "$filename.ts" --onSuccess "node dist/$filename.js"
elif [[ "$1" == *tsx ]]; then
    filename="${filename%.tsx}"
    npx tsup-node "$filename.tsx" --onSuccess "node dist/$filename.js"
else
    echo "Unsupported file extension: $1";
    exit 1
fi
```
