### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module and wrong position of import

### ISSUE THREAD

**Issue by zLupa** [egoist/tsup#608]
I'm using `"type": "module"` in `package.json` and i'm having issus when using the format `cjs` or `esm`

When using `tsup src/* --watch --onSuccess "node dist/main.cjs" --format cjs` this error happens:
![image](https://user-images.githubusercontent.com/56929033/163093872-404a2714-238a-4d87-a1e8-ef1af921fbb4.png)
seems to be because of this:
![image](https://user-images.githubusercontent.com/56929033/163094255-50f6fc65-b97b-49e0-87e6-38adc2c59691.png)

When using `tsup src/* --watch --onSuccess "node dist/main.mjs" --format esm` the import of `reflect-medatata` which is necessary to be the first import before everything is not happening
![image](https://user-images.githubusercontent.com/56929033/163094662-9c064f3b-ffe1-4fa9-bd9a-5a5744e2c037.png)
Also, other error happens when solving that one above
![image](https://user-images.githubusercontent.com/56929033/163094830-ea2b1dcc-5d9b-4c91-9d84-abe6f82c536f.png)

Thanks for the great library!

**Comment by egoist** [comment]
> When using tsup src/* --watch --onSuccess "node dist/main.mjs" --format esm the import of reflect-medatata which is necessary to be the first import before everything is not happening

would love to see a repro

> ![https://user-images.githubusercontent.com/56929033/163094830-ea2b1dcc-5d9b-4c91-9d84-abe6f82c536f.png](https://user-images.githubusercontent.com/56929033/163094830-ea2b1dcc-5d9b-4c91-9d84-abe6f82c536f.png)

you need to `import Prisma from '@prisma/client` (as the error detail suggests)

**Comment by zLupa** [comment]
repo: https://github.com/zLupa/bregabot
just run `yarn dev --format esm` or for cjs `yarn dev --format cjs` output will be in dist folder.

isn't possible to tsup automatically fix that for me?

**Comment by zLupa** [comment]
I solved the issue of the `reflect-metadata` by creating a separate file with the 'import` in there and then importing it into my main file.
