### ISSUE TITLE
how to compile .tsx file with tsup

### ISSUE THREAD

**Issue by HuoXiaoYe** [egoist/tsup#612]
I want to .tsx file with tsup. But i meet a mistake, I want to ask how to configure it, Thanks.
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/48662771/163719184-5e249936-88d9-481f-87be-170e6c3a4883.png">

**Comment by egoist** [comment]
This is a type checking error, you need to enable JSX in tsconfig.json

**Comment by HuoXiaoYe** [comment]
> This is a type checking error, you need to enable JSX in tsconfig.json

It works, Thanks you.
