### ISSUE TITLE
Not support emitDecoratorMetadata

### ISSUE THREAD

**Issue by jsonz1993** [egoist/tsup#626]
how to support emitDecoratorMetadata ?

demo: [https://github.com/jsonz1993/tsup-issues-metadata-demo](https://github.com/jsonz1993/tsup-issues-metadata-demo)

``` 
   ...
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
   ...
```

``` typescript
import 'reflect-metadata'

function Injectable() {
  return function (target: any) {
    return target
  }
}

class AuthService {
  constructor() {}
}

@Injectable()
export class UserService {
  constructor(private authService: AuthService) {}
}
```

tsc
``` javascript
UserService = __decorate([
    Injectable(),
    __metadata("design:paramtypes", [AuthService])
], UserService);
```

tsup
```javascript
UserService = __decorateClass([
  Injectable()
], UserService);
```

**Comment by sidwebworks** [comment]
@jsonz1993 Do you have `@swc/core` installed in your project? esbuild does not preserve any type info, so to make decorators work TSUP uses swc core for getting the decorators to work. (Kevin told me about this in the Discord)

**Comment by jsonz1993** [comment]
wow, install `@swc/core`, the problem is solved

**Comment by sidwebworks** [comment]
@egoist Should we add a warning in the CLI if someone is using `emitDecoratorMetadata` and `@swc/core` is not installed ? I can make a PR.

**Comment by moshest** [comment]
I think it should even throw and not allow using `emitDecoratorMetadata` if `@swc/core` is not installed. I took me a while to figure out what the problem is and it's not documented at all expect for this issue. @egoist
