### ISSUE TITLE
The keyword 'interface' is reserved

### ISSUE THREAD

**Issue by HuoXiaoYe** [egoist/tsup#642]
I used tsup build a package, but when I can't use it in other project. 
<img width="993" alt="image" src="https://user-images.githubusercontent.com/48662771/171003951-07a3fe45-ad5a-4336-9ec8-475349fc07b0.png">
This is my tsup.config.js
<img width="975" alt="image" src="https://user-images.githubusercontent.com/48662771/171004157-716d21c4-01a2-4fd6-b573-459d86ef6afb.png">
Is my config file error?

**Comment by HuoXiaoYe** [comment]
> I used tsup build a package, but when I can't use it in other project. <img alt="image" width="993" src="https://user-images.githubusercontent.com/48662771/171003951-07a3fe45-ad5a-4336-9ec8-475349fc07b0.png"> This is my tsup.config.js <img alt="image" width="975" src="https://user-images.githubusercontent.com/48662771/171004157-716d21c4-01a2-4fd6-b573-459d86ef6afb.png"> Is my config file error?

**Comment by 9oelM** [comment]
You gotta do exactly what the error message says from the first pic. Get a `ts-loader` or anything to parse Typescript when you are using webpack. It's not a problem with tsup, I believe.
