### ISSUE TITLE
Is there a way to specify output directory？

### ISSUE THREAD

**Issue by jay4q** [egoist/tsup#662]
I'm trying to set tsconfig.json `outDir: "../app/functions"`，but not working，`tsup` still put compiled files into `./dist` directory

**Comment by jrson83** [comment]
Yeah you can specify `outDir` option in `tsup.config.ts` `defineConfig` function.

**Comment by jay4q** [comment]
> Yeah you can specify `outDir` option in `tsup.config.ts` `defineConfig` function.

thank u，it works~

the configuration is [here](https://paka.dev/npm/tsup@6.1.2/api#9286de5cf1f8699), and notice there is a [confict](https://github.com/egoist/tsup/issues/303) 🤔️ between tsconfig's `compilerOptions.paths` and tsup.config's `outDir`

hope it will help someone have same issue
