### ISSUE TITLE
No matching version found for tsup@latest

### ISSUE THREAD

**Issue by JusticHentai** [egoist/tsup#683]
when i run `pnpm add tsup`  it say:

ERR_PNPM_NO_MATCHING_VERSION  No matching version found for tsup@latest

The latest release of tsup is "6.2.1".

If you need the full list of all 171 published versions run "$ pnpm view tsup versions".

**Comment by egoist** [comment]
maybe there's something wrong with your npm registry, it works here:
https://registry.npmjs.org/tsup/latest

**Comment by JusticHentai** [comment]
> maybe there's something wrong with your npm registry, it works here: https://registry.npmjs.org/tsup/latest
> […](#)
> Message ID: ***@***.***>

thanks it work
