### ISSUE TITLE
error bundle axios,superagent Uncaught Error: Dynamic require of "util" is not supported

### ISSUE THREAD

**Issue by ajiehatajie** [egoist/tsup#709]
Uncaught Error: Dynamic require of "util" is not supported
    at index.mjs:12:9
    at ../../node_modules/combined-stream/lib/combined_stream.js (index.mjs:2776:16)
    at __require2 (index.mjs:15:17)
    at ../../node_modules/axios/node_modules/form-data/lib/form_data.js (index.mjs:11791:26)
    at __require2 (index.mjs:15:17)
    at ../../node_modules/axios/lib/defaults/env/FormData.js (index.mjs:12104:22)
    at __require2 (index.mjs:15:17)
    at ../../node_modules/axios/lib/defaults/index.js (index.mjs:12200:19)
    at __require2 (index.mjs:15:17)
    at ../../node_modules/axios/lib/core/transformData.js (index.mjs:12226:20)

 "build": "tsup src/index.ts --format esm,cjs --dts --external react axios ",
  "dev": "tsup src/index.ts --format esm,cjs --watch --dts --external react axios",

**Comment by lvqq** [comment]
```
esbuildOptions: (options) => {
  options.banner = {
    js: "import { createRequire } from 'module';const require = createRequire(import.meta.url);";
  }
}
```
Maybe the above `esbuildOption` in `tsup.config.ts` can help it

**Comment by ajiehatajie** [comment]
> import { createRequire } from 'module';const require = createRequire(import.meta.url)

[ERROR] Expected "}" but found "file"

    tsup.config.ts:3:79:
      3 │ ...om 'module';const require = createRequire("file:///Users/legit-group/Documents/Works/Legi...
        │                                               ~~~~
        ╵

**Comment by lvqq** [comment]
It's an related issue with https://github.com/evanw/esbuild/issues/1921, you can try the mentioned solution.

**Comment by mahaoming** [comment]
I also have the same problem. Have you fixed it

**Comment by mahaoming** [comment]
![image](https://user-images.githubusercontent.com/31064550/190567901-c9f9fa34-df48-42af-a5f1-bffc50b4096e.png)

**Comment by mahaoming** [comment]
this is my tsup.config
`export default defineConfig((options: Options) => ({
  entry: ['src/index.ts'],
  dts: true,
  clean: true,
  format: ['esm'],
  esbuildOptions: (options) => {
    options.banner = {
      js: `import { createRequire } from 'module'; const require = createRequire(import.meta.url);`,
    }
  },
  ...options,
}))`

**Comment by mahaoming** [comment]
` typescript
export default defineConfig((options: Options) => ({
  entry: ['src/index.ts'],
  dts: true,
  clean: true,
  format: ['esm'],
  esbuildOptions: (options) => {
    options.banner = {
      js: `import { createRequire } from 'module'; const require = createRequire(import.meta.url);`,
    }
  },
  ...options,
}))
`

**Comment by mahaoming** [comment]
> Uncaught Error: Dynamic require of "util" is not supported at index.mjs:12:9 at ../../node_modules/combined-stream/lib/combined_stream.js (index.mjs:2776:16) at __require2 (index.mjs:15:17) at ../../node_modules/axios/node_modules/form-data/lib/form_data.js (index.mjs:11791:26) at __require2 (index.mjs:15:17) at ../../node_modules/axios/lib/defaults/env/FormData.js (index.mjs:12104:22) at __require2 (index.mjs:15:17) at ../../node_modules/axios/lib/defaults/index.js (index.mjs:12200:19) at __require2 (index.mjs:15:17) at ../../node_modules/axios/lib/core/transformData.js (index.mjs:12226:20)
> 
> "build": "tsup src/index.ts --format esm,cjs --dts --external react axios ", "dev": "tsup src/index.ts --format esm,cjs --watch --dts --external react axios",

Did you solve it

**Comment by lvqq** [comment]
`tsup` has an bug with banner, refer: https://github.com/egoist/tsup/issues/719, just try other solution

**Comment by mahaoming** [comment]
> you need `--external react --external axios` to externalize both modules instead of `--external react axios`

had add external, but it not work for me

**Comment by mahaoming** [comment]
> you need `--external react --external axios` to externalize both modules instead of `--external react axios`

![image](https://user-images.githubusercontent.com/31064550/207892798-cd1071fe-421d-4cfa-91f5-935a4fd0718c.png)

**Comment by amosmachora** [comment]
I don't think there is a clear answer. Still running into the same problem. 

i use tsup in my ci/cd pipeline

` "build": "tsup index.ts --format cjs,esm --dts --external axios",`

I don't have a tsup.config file. Should i add one and if so what should i add to get rid of the error. 
_Error: Dynamic require of "axios" is not supported_

**Comment by amosmachora** [comment]
> you need `--external react --external axios` to externalize both modules instead of `--external react axios`

This doesn't seem to work
