### ISSUE TITLE
Feature request: add support for jsxImportSource

### ISSUE THREAD

**Issue by stevenle** [egoist/tsup#715]
https://esbuild.github.io/api/#jsx-import-source
^ relevant esbuild docs

**Comment by gavinsharp** [comment]
As of [v6.2.2](https://github.com/egoist/tsup/releases/tag/v6.2.2), tsup is using [a version of esbuild that supports the new JSX transform](https://github.com/evanw/esbuild/releases/tag/v0.14.51), so you should be able to specify `jsxImportSource` via `tsconfig.json` and have tsup/esbuild pick it up automatically.

**Comment by stevenle** [comment]
@gavinsharp thanks for the heads up, just upgraded and tested, working as expected!

**Comment by shellscape** [comment]
@gavinsharp as of 8.0.0, `jsxImportSource` doesn't exist on the `Options` type. And tsup doesn't even pass `jsxImportSource` to esbuild if you pass it with `as any`. Simply doesn't work.

**Comment by gavinsharp** [comment]
> @gavinsharp as of 8.0.0, `jsxImportSource` doesn't exist on the `Options` type. And tsup doesn't even pass `jsxImportSource` to esbuild if you pass it with `as any`. Simply doesn't work.

I was suggesting `esbuild` would read `jsxImportSource` directly from the tsconfig on its own, independently of `tsup`. It's possible something has changed since, but that was working for me when I made the comment.

**Comment by shellscape** [comment]
Ah distinct difference there. I've a patch that I'm going to open a PR for that adds support to the `Options` so tsconfig doesn't have to be relied upon.

**Comment by bertho-zero** [comment]
To build js you don't have `tsconfig.json` and you have to add this to `tsup.config.js` to not get the error "React is not defined":

```js
  esbuildOptions(options) {
    options.jsx = 'automatic';
  },
```
