### ISSUE TITLE
"tsup-node" doesn't respect "noExternal" configuration

### ISSUE THREAD

**Issue by eric-burel** [egoist/tsup#718]
Hi,

I've been using "[tsup-node to exclude all packages](https://tsup.egoist.dev/#excluding-all-packages)" with great pleasure to build some scripts while excluding all node_modules.

I am refactoring a monorepo, and I am in the special case where I have internal NPM packages that expose pure .ts code.
Therefore, I need those specific packages to be included in the build, despite being listed in the package.json.

The use case is pretty close to what's described for next-transpile-modules: https://www.npmjs.com/package/next-transpile-modules "code transpilation from local packages (think: a monorepo with a styleguide package)". 

What's the equivalent in Tsup? How can we forcibly reinclude some packages while using tsup-node?

Here is an example: https://github.com/Devographics/Monorepo/pull/117, the scripts are built in the "surveyform" directory, alongside the Next app. Package "core-models" lives in the shared folder, you can see how the package.json let's us expose pure TS files. I need this specific package to be bundled despite it being listed in package.json as a dependency.

**Comment by VladimirGrenaderov** [comment]
@eric-burel is https://github.com/egoist/tsup/discussions/538 can help?

**Comment by eric-burel** [comment]
@VladimirGrenaderov great tip thank you, however I don't really see the effect of this command, the built file is completely similar. The option is read (if I put a wrong string instead of an array it fails) but has no effect.

Example config:

```
const commonConfig = {
  clean: true,
  splitting: false,
  // Skip until .d.ts.map is also supported https://github.com/egoist/tsup/issues/564
  // dts: true,
  sourcemap: true,
  tsconfig: path.resolve(__dirname, "./tsconfig.tsup.json"),
  outDir: "scripts/dist",
  name: "",
  platform: "node" as const,
  target: "node14",
  noExternal: [/^@devographics($|\/)/],
  esbuildPlugins: [yamlPlugin({})],
};
```

Note that this is with "tsup-node" not "tsup" as I build a Node script.

**Comment by eric-burel** [comment]
#718 fixes but if someone needs it right now, they can use this config with `tsup` in replacement to tsup-node:
```
// whatever you need to bundle (here my shared "@devographics" internal packages and my path alias "~")
  noExternal: [/^@devographics($|\/)/, /^~/],
// everything else (this regexp is taken from the code used when tsup-node or skipNodeModulesBundle option are used)
  external: [/^[^.\/]|^\.[^.\/]|^\.\.[^\/]/],
```
