### ISSUE TITLE
why I get { default: [Getter] }?

### ISSUE THREAD

**Issue by classmatewu** [egoist/tsup#745]

**Comment by classmatewu** [comment]
### background
I used tsup to bundle my typescript file,and foramt esm and cjs, but when I require the cjs, I found it not as expected

### test.ts
```typescript
const a: 1 = 1
export default a
```

### script
```bash
"build": "tsup-node ./src/ts.ts --format cjs,esm --dts --sourcemap"
```

### require
```bash
const a = require("./dist/test.js")
console.log(a);
```

### result
{ default: [Getter] }

### my expected
log 1

### version
tsup/6.2.3 darwin-x64 node-v14.16.0

**Comment by lvqq** [comment]
Use `const a = require("./dist/test.js").default` instead

**Comment by classmatewu** [comment]
I don't think it should be done, not good enough

**Comment by lvqq** [comment]
esm transform to cjs do add a `default` field I think.

**Comment by hyrious** [comment]
If `require("./dist/test.js")` returns literal `1`, how would you expect the named export `a` to be captured in CJS context? Consider `require("./dist/test.js").a` will be evaluated to `1 .a`, which is `undefined` and not your expectation too.

Read more about [default interop](https://esbuild.github.io/content-types/#default-interop).

**Comment by classmatewu** [comment]
@hyrious 
You don't seem to understand the meaning of the question?

I want `require("./dist/test.js").a`to be 1, instead of { default: {a: 1} }

**Comment by hyrious** [comment]
That's not the semantic of `export default a`. These 2 codes are the same:

```js
const a = 1
export default a
```

```js
export default 1
```

They both export a _default_ value of `1`, the name `a` is dropped.

You should write this instead if you want a named export:

```js
export const a = 1
```

**Comment by classmatewu** [comment]
thanks a lot.
