### ISSUE TITLE
Watch specific files?

### ISSUE THREAD

**Issue by SachaG** [egoist/tsup#751]
My project contains `.graphql` files and `.yaml` files, which are not being watched by tsup (they don't trigger a reload when modified). Is there a way to add them to the list of watched files?

Additionally, the YAML files are actually in a different directory. Does that change anything?

**Comment by await-ovo** [comment]
I think `tsup --watch . --watch ./some-file` should work as expected ~

**Comment by SachaG** [comment]
That worked, thanks!
