### ISSUE TITLE
tsub is not command

### ISSUE THREAD

**Issue by Mustafa-Zahedi** [egoist/tsup#766]
tsub : The term 'tsub' is not recognized as the name of a cmdlet, function, script file, or operable 
program. Check the spelling of the name, or if a path was included, verify that the path is correct and  
try again.

**Comment by await-ovo** [comment]
should it be tsup ?

**Comment by Mustafa-Zahedi** [comment]
oh sorry, I installed by this command `npm i tsup -D` and then `tsup index.js` in powershell terminal but again it is not recognized, if may publish a short video for getting started. 
thanks

**Comment by await-ovo** [comment]
did you use `npm run tsup index.js` ?

**Comment by egoist** [comment]
you should run `npx tsup` to run locally installed tsup or add `tsup` to your npm scripts and use `npm run <your-npm-script>`

**Comment by Mustafa-Zahedi** [comment]
thanks guys for your guides. I thinks the Docs should be clear.
