### ISSUE TITLE
[Doc] clarify target property valid values

### ISSUE THREAD

**Issue by FossPrime** [egoist/tsup#769]
https://github.com/egoist/tsup/blob/48b3381b15562490870b0cf32f15252038958384/src/options.ts#L65

What are the values for target? SWC has similarly poor documentation on this, and it doesn't correlate to tsconfig.

I couldn't find anything.

This is the closest thing I found to an answer, indicating node18 is not a supported target:
https://github.com/swc-project/swc/blob/13b4d317a5fc595f7446250ca9da570e3586cff4/yarn.lock#L1770

**Comment by egoist** [comment]
Added a section for this: https://tsup.egoist.dev/#target-environment
