### ISSUE TITLE
dts logs printed after build promise completes

### ISSUE THREAD

**Issue by scheibo** [egoist/tsup#776]
Currently using version 6.5.0:

The following prints `hi` before `reportSizes` for DTS gets logged:

```js
  await tsup.build({
    entry: files,
    outDir: 'build',
    format: ['cjs', 'esm'],
    sourcemap: true,
    splitting: true,
    dts: true
  });

console.log(`\nProducing \x1b[96m${outfile}\x1b[0m for \x1b[34m@pkmn/${pkg}\x1b[0m...`);
```

From my actual project:

![logs](https://cdn.discordapp.com/attachments/584106305149468672/1042637003092668537/Screen_Shot_2022-11-16_at_19.07.04.png)

Presumably this is due to rollup being run in a `Worker` and the future chain not being propagated appropriately, though from looking at the code myself I didn't see anything obvious

**Comment by await-ovo** [comment]
seems related to https://github.com/nodejs/node/issues/30491
