### ISSUE TITLE
Wrong (default) `tsconfig.json` used even though custom one is provided in tsup config

### ISSUE THREAD

**Issue by mkosir** [egoist/tsup#791]
I have my own tsconfig file path defined to be used for tsup
```ts
// tsup.config.ts
{
  entry: ['src/export-types/index.ts'],
  dts: { only: true },
  clean: true,
  tsconfig: 'tsconfig.build.json',
}
```
which has `incremental: false`
```ts
// tsconfig.build.json
{
  "compilerOptions": {
    ...
    "incremental": false,
    ...
}
```

Somehow tsup still pick up my (default) `tsconfig.json`, thats in the root of the project, which has `"incremental": true` and fails with an error:
```sh
CLI Building entry: src/export-types/index.ts
CLI Using tsconfig:tsconfig.build.json  <-- notice that tsup output in terminal states correct/defined tsconfig file
CLI tsup v6.5.0
CLI Using tsup config: tsup.config.ts
DTS Build start
error TS5074: Option '--incremental' can only be specified using tsconfig, emitting to single file or when option '--tsBuildInfoFile' is specified.
```

If I delete `tsconfig.json` in root folder (that of course must be present for VS code to pick it up, and for development config), tsup bundles with defined/correct `tsconfig.build.json` and no error.

**Comment by await-ovo** [comment]
It looks like `rollup-plugin-dts` will still load `tsconfig.json` even though `tsup` provides a way to customize the tsconfig path: https://github.com/Swatinem/rollup-plugin-dts/blob/master/src/program.ts#L38
