### ISSUE TITLE
What kind of things can we bundle?

### ISSUE THREAD

**Issue by mesqueeb** [egoist/tsup#8]
I'm interested in `.vue` files with `lang="ts"` in the script tag. Is this possible with tsup?

**Comment by egoist** [comment]
Currently it's only for projects with js, ts files, but I'll consider adding built-in Vue support.

**Comment by egoist** [comment]
I wonder if `rollup-plugin-vue` could generate TypeScript code so I can somehow make rollup-plugin-dts use it to generate declaration file, otherwise I'll have to implement my own version of `rollup-plugin-vue` 😅 /cc @znck

**Comment by znck** [comment]
Sorry, It’s out of scope. 

You can create one and to generate typescript output for template you need to create a separate compiler. I have create on for tsserver plugin: https://github.com/znck/vue-developer-experience/tree/master/packages/%40vuedx/compiler-typescript.

**Comment by egoist** [comment]
I replaced Rollup with esbuild, so we need to wait for esbuild's plugin API to add Vue support.

**Comment by mesqueeb** [comment]
@egoist I see! Why the change to esbuild?

**Comment by egoist** [comment]
It's much much faster, and this project is mainly for Nodejs libs so we can use esbuild without problems, soon esbuild will support plugins, we will add Vue support later.

**Comment by mesqueeb** [comment]
Nice!

**Comment by mesqueeb** [comment]
Nice!
I'm still looking for a way to write TypeScript vue components that can be bundled with actual type information on its props.

Do you think that the esbuild Vue plugin will be able to do that as well?

(for [Vue-compile](https://github.com/egoist/vue-compile/issues/146) this is also still an open issue)

**Comment by DannyFeliz** [comment]
I wish we can have this one day

**Comment by productdevbook** [comment]
when support vue ?

**Comment by gustawdaniel** [comment]
There is a project https://github.com/egoist/esbuild-plugin-vue but I was not able to run it successfully.
