### ISSUE TITLE
Enable babel transform

### ISSUE THREAD

**Issue by egoist** [egoist/tsup#80]
By passing a flag `--babel` tsup should load `@babel/core` and `babel.config.js` from your project directory to transform the code. This should also disable built-in es5 transform since you can use `@babel/preset-env` instead.

**Comment by 9oelM** [comment]
Hi @egoist, is this flag still supported? seems like I must be doing something wrong. tsup emits an error on receiving `--babel`.

![image](https://user-images.githubusercontent.com/22465806/173290678-e47d6f00-b94f-4d07-a03e-403b5cd35e68.png)

**Comment by egoist** [comment]
@9oelM it's been removed
