### ISSUE TITLE
Upgrade to esbuild@^0.16

### ISSUE THREAD

**Issue by segevfiner** [egoist/tsup#810]
Just what it says on the title, tsup currently uses esbuild@^0.15

**Comment by segevfiner** [comment]
By now esbuild@^0.17 has been released

**Comment by code0wl** [comment]
It feels like tsup is not maintained anymore...

**Comment by segevfiner** [comment]
> It feels like tsup is not maintained anymore...

I sure hope not...

**Comment by segevfiner** [comment]
tsup v6.6.0 was released with an upgrade to 0.17.
