### ISSUE TITLE
Support .mts for config file?

### ISSUE THREAD

**Issue by zeakd** [egoist/tsup#818]
Hi. How do you think about support `tsup.config.mts` (and also `tsup.config.cts`? 
`tsup.config.ts` shows up type error in `{ "module": "Node16" }` environment when use mjs specific feature like `import.meta`

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/egoist) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/egoist/tsup/issues/818">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/egoist/tsup/issues/818/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/egoist/tsup/issues/818/pledge.svg">
</picture>
</a>

**Comment by luozhihua** [comment]
Same
