### ISSUE TITLE
Consider out directory override per file format

### ISSUE THREAD

**Issue by benjreinhart** [egoist/tsup#823]
Forgive me if this is already possible to do, though it didn't seem like it...

It might be nice in some situations to fully customize the output path _per file_. We already have something that is close, `outExtension`, which takes a function, but it would be good to be able to customize the full path.

I'm thinking something that would allow us to change the folder as well, e.g.:

```ts
export default defineConfig({
  out({filename, format}) {
    return format === "esm" ? `lib/esm/${filename}.js` : `lib/${filename}.js`;
  },
});
```

**Comment by christianarty** [comment]
There is support for it. The `defineConfig` can take either `Options` or `Options[]`, so you can have a `defineConfig` like this:
```javascript
export default defineConfig([
  {
    entry: ['src/**/*.ts'],
    format: ['esm'],
    outDir: 'dist/esm', // ESM only directory
    target: 'node16',
  },
  {
    entry: ['src/**/*.ts'],
    format: ['cjs'],
    outDir: 'dist/cjs', // CommonJS only directory
    target: 'node16',
  },
]);
```
and this would effectively be the way you go and do multiple output folders.

Additionally, in either one, you can customize the output even further, by adding an `outExtension` function.

**Comment by benjreinhart** [comment]
@christianarty that does look like what I was thinking, appreciate it
