### ISSUE TITLE
How to force tsup to not compile when I have an error in .ts code?

### ISSUE THREAD

**Issue by marco-carvalho** [egoist/tsup#851]
I have this `tsconfig.json`:
```
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "noEmitOnError": true
  }
}
```

And I have this `index.ts`:
```
const add = (n1, n2) => n1 + n2;
var x = add(1,2);
console.log(x);
```

If I run `npx tsc`, I get the following errors:
```
index.ts:1:14 - error TS7006: Parameter 'n1' implicitly has an 'any' type.

1 const add = (n1, n2) => n1 + n2;
               ~~

index.ts:1:18 - error TS7006: Parameter 'n2' implicitly has an 'any' type.

1 const add = (n1, n2) => n1 + n2;
                   ~~


Found 2 errors in the same file, starting at: index.ts:1
```

Because I defined `"noEmitOnError": true`, there was no `index.js`, and that's exactly what I wanted.

How can I achieve the same behaviour with `tsup`? Because when I run `tsup index.ts`, it creates a `dist/index.js`.

**Comment by hyrious** [comment]
How about `tsc --noEmit && tsup index.ts`

**Comment by marco-carvalho** [comment]
@hyrious I think I'm gonna used it like your example, but I thought this kinda of behaviour existed in `tsup`...
