### ISSUE TITLE
Having a hard time to understand why "tsup" is only bundling "devDependencies" packages

### ISSUE THREAD

**Issue by marco-carvalho** [egoist/tsup#852]
I have this `index.ts`:
```ts
import express from 'express';

const app = express();

app.get('/', (req, res) => {
    res.send("Hello, world!");
});

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});
```

And I have this `dependencies` and `devDependencies` in my `package.json`:
```json
  "devDependencies": {
    "tsup": "6.6.3",
    "typescript": "4.9.5"
  },
  "dependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^18.14.6",
    "express": "^4.18.2"
  }
```

When I run `tsup index.ts`, it generates a `dist\index.js` with 1.42 KB. Then I try to run it in my server, and I get this error:
```
$ node index.js 
node:internal/modules/cjs/loader:1063
  throw err;
  ^

Error: Cannot find module 'express'
``` 

So I moved `express` from `dependencies` to `devDependencies` in my `package.json`:
```json
  "devDependencies": {
    "express": "^4.18.2",
    "tsup": "6.6.3",
    "typescript": "4.9.5"
  },
  "dependencies": {
    "@types/express": "^4.17.17",
    "@types/node": "^18.14.6"
  }
```

When I run `tsup index.ts`, it generates a `dist\index.js` with 1.12 MB. Then I try to run it in my server, and everything works:
```
$ node index.js
Server listening on port 3000
```

My question is: I desire to use `express` in the final bundle, so I thought I should put in the `dependencies` node, and others development dependencies (like `typescript`) should be in the `devDependencies` node. But for this workflow to work, I'm having to put `express` in the `devDependencies` node, which for me doesn't make sense. Am I missing something?

**Comment by hyrious** [comment]
Here's the case: tsup is made for **libraries**, which is not supposed to run individually.

Libraries are supposed to **be installed**, during the installation, package managers (npm) will fetch all `dependencies` and install them too. So there's no need for a library to bundle its dependencies.

If you're searching for a bundler that bundles all your code to one big bundle.js, then I'd recommended you to use [esbuild](https://esbuild.github.io/), which is also the library that tsup depends on. (See, esbuild is not bundled in tsup too.)

**Comment by marco-carvalho** [comment]
thank you @hyrious
