### ISSUE TITLE
Custom tsconfig isn't working

### ISSUE THREAD

**Issue by ComLock** [egoist/tsup#893]
I've tried --tsconfig on the cmdline, tsconfig and esbuildOptions(options) options.tsconfig in the tsup.config.ts file, nothing works.

In your test if I add

```"target": "es5"```

to compilerOptions, and

```'--format','cjs',```

it should fail with

```
✘ [ERROR] Transforming const to the configured target environment ("es5") is not supported yet
```

But it doesn't.

So I think the test is too simple and doesn't actually test that the custom tsconfig file is used.

**Comment by jerrywu001** [comment]
Follow your steps, I got the correct message

![image](https://user-images.githubusercontent.com/12525415/234741694-ab106cbc-3b9f-486a-80b2-88a3bcde9fad.png)


``` ts
test.only('simple', async () => {
  const { output, outFiles } = await run(
    getTestName(),
    {
      'input.ts': `import foo from './foo'; export default foo`,
      'foo.ts': `export default 'foo'`,
    },
    {
      flags: ['--format', 'cjs'],
    }
  )
  expect(output).toMatchSnapshot()
  expect(outFiles).toEqual(['input.js'])
})
```

- `npm run test-only`

`X [ERROR] Transforming const to the configured target environment ("ES5") is not supported yet`

![image](https://user-images.githubusercontent.com/12525415/234741802-d11c3943-d467-45cd-b2a4-9c42943f2d02.png)

**Comment by jerrywu001** [comment]
- ✅ Use esbuild script
- ✅ Use tsconfig.json
 - ❌ Use custom.config.json
 - ❌ Use esbuildOptions

## Use esbuild script

![image](https://user-images.githubusercontent.com/12525415/234777500-0fd0227b-e9df-4038-b0c9-d23201c643ff.png)

 
### Use tsconfig.json

![image](https://user-images.githubusercontent.com/12525415/234775576-2b0498f4-80f7-479e-b748-85698b2d6a73.png)

### Use custom.config.json

- tsconfig.json

```json
{
  "compilerOptions": {
    "module": "esnext",
    "declaration": true,
    "declarationDir": "dist",
    "outDir": "./dist",
    "strict": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

![image](https://user-images.githubusercontent.com/12525415/234776048-605de864-c68c-48fd-9593-8f45d7d5fbde.png)

### Use esbuildOptions

- tsup.config.ts

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  esbuildOptions(options) {
    options.tsconfig = 'custom.tsconfig.json'
  },
  entry: ['input.ts'],
})
```

![image](https://user-images.githubusercontent.com/12525415/234778641-af497bf8-24e2-4a72-827b-635927b5af69.png)

**Comment by jerrywu001** [comment]
- ✅ Use esbuild script
- ✅ Use tsconfig.json
 - ❌ Use custom.config.json
 - ❌ Use esbuildOptions

Actually, the esbuild does not output error messages

![image](https://user-images.githubusercontent.com/12525415/234797869-ad325bc8-c35f-40c6-9f7d-d0c9dcecbf5c.png)

## Use esbuild script

![image](https://user-images.githubusercontent.com/12525415/234777500-0fd0227b-e9df-4038-b0c9-d23201c643ff.png)
 
### Use tsconfig.json

![image](https://user-images.githubusercontent.com/12525415/234775576-2b0498f4-80f7-479e-b748-85698b2d6a73.png)

### Use custom.config.json

![image](https://user-images.githubusercontent.com/12525415/234776048-605de864-c68c-48fd-9593-8f45d7d5fbde.png)

But after editing node_modules/tsup/index.js, and re-running the script, it is ok.

![image](https://user-images.githubusercontent.com/12525415/234845864-60523dea-008a-4b14-9bc9-527ee177902c.png)


### Use esbuildOptions

- tsup.config.ts

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  esbuildOptions(options) {
    options.tsconfig = 'custom.tsconfig.json'
  },
  entry: ['input.ts'],
})
```

![image](https://user-images.githubusercontent.com/12525415/234778641-af497bf8-24e2-4a72-827b-635927b5af69.png)

**Comment by jerrywu001** [comment]
```ts
test.only('simple', async () => {
  const { outFiles } = await run(
    getTestName(),
    {
      'input.ts': `import foo from './foo';export default foo;`,
      'foo.ts': `const foo = 'foo';export default foo;`,
      'custom.tsconfig.json': `{
        "compilerOptions": {
          "baseUrl": ".",
          "rootDir": "./",
          "target": "es5",
          "module": "esnext",
          "declaration": true,
          "declarationDir": "dist",
          "outDir": "./dist",
          "strict": true,
          "moduleResolution": "node",
          "esModuleInterop": true,
          "resolveJsonModule": true,
          "skipLibCheck": true,
          "forceConsistentCasingInFileNames": true
        }
      }`
    },
    {
      flags: ['--format', 'cjs', '--tsconfig', 'custom.tsconfig.json'],
    }
  )
  // expect(output).toMatchSnapshot()
  expect(outFiles).toEqual(['input.js'])
})
```

- ✅ Use esbuild script
- ✅ Use tsconfig.json
 - ❌ Use custom.config.json (can fix)
 - ❌ Use esbuildOptions

Actually, the esbuild does not output error messages

![image](https://user-images.githubusercontent.com/12525415/234797869-ad325bc8-c35f-40c6-9f7d-d0c9dcecbf5c.png)

## Use esbuild script

![image](https://user-images.githubusercontent.com/12525415/234777500-0fd0227b-e9df-4038-b0c9-d23201c643ff.png)
 
### Use tsconfig.json

![image](https://user-images.githubusercontent.com/12525415/234775576-2b0498f4-80f7-479e-b748-85698b2d6a73.png)

### Use custom.config.json

![image](https://user-images.githubusercontent.com/12525415/234776048-605de864-c68c-48fd-9593-8f45d7d5fbde.png)

**But after editing node_modules/tsup/index.js, and re-running the script, it can report the error**. @egoist 

![image](https://user-images.githubusercontent.com/12525415/234851651-8ba77e96-4dac-4439-a09e-39f2d04bf6d2.png)

### Use esbuildOptions

- tsup.config.ts

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  esbuildOptions(options) {
    options.tsconfig = 'custom.tsconfig.json'
  },
  entry: ['input.ts'],
})
```

![image](https://user-images.githubusercontent.com/12525415/234778641-af497bf8-24e2-4a72-827b-635927b5af69.png)

**Comment by jerrywu001** [comment]
``` ts
test.only('simple', async () => {
  const { outFiles } = await run(
    getTestName(),
    {
      'input.ts': `import foo from './foo'; export default foo;`,
      'foo.ts': `const foo = 'foo';export default foo;`, // add const keyword
      'custom.tsconfig.json': `{
        "compilerOptions": {
          "baseUrl": ".",
          "rootDir": "./",
          "target": "es5",
          "module": "esnext",
          "declaration": true,
          "declarationDir": "dist",
          "outDir": "./dist",
          "strict": true,
          "moduleResolution": "node",
          "esModuleInterop": true,
          "resolveJsonModule": true,
          "skipLibCheck": true,
          "forceConsistentCasingInFileNames": true
        }
      }`
    },
    {
      flags: ['--format', 'cjs', '--tsconfig', 'custom.tsconfig.json'],
    }
  )
  expect(outFiles).toEqual(['input.js'])
})
```

- ✅ Use esbuild script
- ✅ Use tsconfig.json
 - ❌ Use custom.config.json (can fix)
 - ❌ Use esbuildOptions

Actually, the esbuild does not output error messages

![image](https://user-images.githubusercontent.com/12525415/234797869-ad325bc8-c35f-40c6-9f7d-d0c9dcecbf5c.png)

### Use custom.config.json

![image](https://user-images.githubusercontent.com/12525415/234776048-605de864-c68c-48fd-9593-8f45d7d5fbde.png)

**But after editing node_modules/tsup/index.js, and re-running the script, it can report the error**. @egoist 

![image](https://user-images.githubusercontent.com/12525415/234851651-8ba77e96-4dac-4439-a09e-39f2d04bf6d2.png)

### Use esbuildOptions

- tsup.config.ts

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  esbuildOptions(options) {
    options.tsconfig = 'custom.tsconfig.json'
  },
  entry: ['input.ts'],
})
```

![image](https://user-images.githubusercontent.com/12525415/234778641-af497bf8-24e2-4a72-827b-635927b5af69.png)

**Because the target is not assigned to `es5`, it is now `esnext` by default**

**We need to reset the target from [custom.tsconfig.json]** @egoist 

``` ts
test.only('simple', async () => {
  const { output, outFiles } = await run(
    getTestName(),
    {
      'input.ts': `import foo from './foo'; export default foo;`,
      'foo.ts': `const foo = 'foo';export default foo;`,
      'tsup.config.ts': `import path from 'path';
export default {
  esbuildOptions(options) {
    options.tsconfig = 'custom.tsconfig.json'
    // options.target = 'es5'; // -----> need reset the target from [custom.tsconfig.json]
  },
}`,
      'custom.tsconfig.json': `{
        "compilerOptions": {
          "baseUrl": ".",
          "rootDir": "./",
          "target": "es5",
          "module": "esnext",
          "declaration": true,
          "declarationDir": "dist",
          "outDir": "./dist",
          "strict": true,
          "moduleResolution": "node",
          "esModuleInterop": true,
          "resolveJsonModule": true,
          "skipLibCheck": true,
          "forceConsistentCasingInFileNames": true
        }
      }`
    },
    {
      flags: ['--format', 'cjs'],
    }
  )
  // expect(output).toMatchSnapshot()
  expect(outFiles).toEqual(['input.js'])
})
```

**Comment by ComLock** [comment]
Actually the custom tsconfig is working.

I was confused by the error messages.

They are NOT from esbuild when transpiling the source code,
they are from esbuild when transpiling the tsup.config.ts file.

In other words: Don't set target: "es5" in the tsconfig.js file, because it will be used to transpile the tsup.config.ts file (and that transpilation doesn't use swc).

In stead set target to "es5" via commandline --target, or in tsup.config.ts, or if you configure a custom tsconfig file, you can set it there aswell.

Don't set target to es5 in under tsup.config.ts esbuildOptions, because esbuild actually don't support es5 yet.

**Comment by ComLock** [comment]
Sidenote: https://github.com/egoist/bundle-require/issues/38

**Comment by jerrywu001** [comment]
actually, if you configure a custom tsconfig file, the target can not pass to tsup config.
