### ISSUE TITLE
Is there a js api in tsup?

### ISSUE THREAD

**Issue by johann1301s** [egoist/tsup#922]
Is there a js api in tsup?

For example something like:

```js
import {build} from 'tsup'

build({
   index: '...',
   config: { ... }
})
```

**Comment by johann1301s** [comment]
I see from the d.ts file that there is indeed a `build` function exported. However, I can not find this in the docs...

**Comment by wootencl** [comment]
I too am curious about using the exposed `build` function. @johann1301s were you able to use/verify it offers parity to the CLI API?

**Comment by wootencl** [comment]
Now I feel silly as there's clearly a Type Doc link on the tsup web page. Many thanks for pointing that out and updating the docs @ocavue! 🙏
